<h1>Atividades</h1>
<br />

<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'atividades','action'=>'new')); ?>"><i class="icon-plus"></i>Nova Atividade</a>
</p>
<?php

    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp'], 'hidden'),
                $this->FormDefault(['nome' => 'text']),
            "</td>\r<td>",
                $this->FormDefault(['ocupacao' => 'select']),
            "</td>\r<td>",
                $this->FormDefault(['status' => 'select']),
            "</td>\r<td style='vertical-align: middle;'>",
                $this->FormDefault(['enviar'], 'submitOnly'),
            "</td>\r",
        $this->FormDefault([],'fim');
    }
    
$coluns = array('ID','Descrição','Ocupação','Criado Em','Status');
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'first'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getDescricao(),
        //$entity->getCodSeguradora(),
        $entity->getOcupacao('str'),
        $entity->getCriadoEm(),
        $entity->getStatus(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="GET">
    <input type="hidden" name="subOpcao" id="subOpcao">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'index')); ?>";
        envia(tar,'buscar',formName);
    }  
    function edit(id){
        var tar = "<?php echo $this->url('livraria-admin-interna',array('controller'=>'atividades','action'=>'edit','id'=>'')); ?>";
        envia(tar + id);
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url('livraria-admin-interna',array('controller'=>'atividades','action'=>'delete','id'=>'')); ?>";
        envia(tar + id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>