<h1>Escolha uma opção.</h1>
<br />
<br />
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'buscar')); ?>">Buscar e Gerar Mensais para Renovação.</a>
</p>
<!--
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'listarRenovados')); ?>">Listar Mensais em Renovação.</a>
</p>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'buscarAbertos')); ?>">Fechar Mensais em Renovação.</a>
</p>
-->
<br />
<br />