<h1>Escolha uma opção.</h1>
<br />
<br />
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'listarRenovados')); ?>">Listar Renovados.</a>
</p>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'buscar')); ?>">Buscar Fechados para Renovação.</a>
</p>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'renovacaos','action'=>'buscarAbertos')); ?>">Renovados a serem fechados.</a>
</p>
<br />
<br />