<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<h1>Listar Renovados</h1>
<br />
<style type="text/css">
#delobs {
    left:150px;
    margin:0;
    padding:10px;
    position:absolute;
    top:50%;
    width:650px;
    background-color: #ffffff;
    border: solid #000 1px;
}
</style>

<?php
    $form = $this->form; 
    $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
    $form->prepare();
    echo 
    $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
        "<td>\r",
            $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp','user'], 'hidden'),
            $this->FormDefault([
                'name' => 'usuarioNome',
                'icone' => 'icon-search',
                'js' => 'autoCompUsuario()',
                'span' => "popUser' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['id'], 'text'),
        "</td><td>\r",
            $this->FormDefault(['dataI'], 'calend'),
        "</td><td>\r",
            $this->FormDefault(['dataF'], 'calend'),
        "</td><td>\r",
        "</td><td style='vertical-align: middle;' rowspan='2'>\r",
            $this->FormDefault(['enviar'], 'submitOnly'),
        "</td>\r",
    "</tr><tr>\r",
        "<td>\r",
            $this->FormDefault(['administradora'=>'hidden']),
            $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['status'=>'radio']),
        "</td><td>\r",
            $this->FormDefault(['validade'=>'radio']),
        "</td><td>\r",
        "</td>\r",

    $this->FormDefault([],'fim');

$coluns = array(
    'Ação',
    'ID',
    'S',
    'Administradora',
    'Atividade',
    'Classe',
    'Inicio',
    'Fim',
    'Locador',
    'Locatario',
    'Valor',
    'Status'
    );
$td     = array(
    'nowrap',
    'nowrap class="r"',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap'
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'firt'));

$lambda = function($value,&$data){
        echo "\t<td nowrap>";
        switch ($data[11]) {
            case "C":
                echo '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs</span>';
                break;
            case "F":
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>',
                     '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs</span>';
                break;
            case "A":
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>',
                     '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Del.</span>';   
                break;
            default:
                echo '<span class="add-on hand">Sem Ação</span>';
        }
        echo "</td>\n"; 
    };
    
$this->ViewIndex('setFuncEdit',$lambda); 

foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getId() .'/'. $entity->getCodAno(),
        substr($entity->getSeguradora(),0,1),
        $entity->getAdministradora(),
        $entity->getAtividade(),
        $entity->getTaxa()->getClasse(),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->floatToStr('premioTotal'),
        $entity->getStatus(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
    <input type="hidden" name="renovacao" id="renovacao">
<div id="delobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoNaoFechou">Motivo do cliente não renovar.</label>
                    <textarea name="motivoNaoFechou" id="motivoNaoFechou" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir()"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:deleltar();"><i class="icon-trash"></i>Finalizar!</a>
            </td>
        </tr>
    </table>
</div> 
</form> 
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    var formName = '<?php echo $this->formName ?>';
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    } 
    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    }
    function getLogs(id){
        document.getElementById('id2').value = id ;
        document.getElementById('renovacao').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'logs','action'=>'logRenovacao')); ?>";
        envia(tar,id);        
    }
    function del(id){
        var motivo = document.getElementById('delobs');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar esta renovação?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;
    }  
    function desistir(){
        document.getElementById('delobs').style.display='none';
        document.getElementById('id2').value = '' ;
    }
    function deleltar(){
        var id = document.getElementById('id2').value;
        var obs = document.getElementById('motivoNaoFechou').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
        }
        if(id == '')return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        envia(tar,id);        
    }

    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }  

    document.getElementById('delobs').style.display = 'none';
    
    $(document).ready(function(){
        var y_fixo = 500 + $("#delobs").offset().top;
        $(window).scroll(function () {
            $("#delobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
        });
    });

    function buscar(){
        if(document.getElementById('usuarioNome').value == ''){
            document.getElementById('user').value = '';
        }
        if(document.getElementById('administradoraDesc').value == ''){
            document.getElementById('administradora').value = '';
        }
        if(document.getElementById('administradora').value == ''){
            if(document.getElementById('dataI').value == ''){
                if(document.getElementById('id').value == ''){
                    alert('Atenção é necessário preencher alguns filtro:\n Ex: Administradora ou Periodo ou Nº do Orçamento!');
                    return false;
                }
            }
        }
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'listarRenovados')); ?>";
        envia(tar,'buscar',formName);
        return false;
    }  
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>