<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<h1>Listar Renovados</h1>
<br />
<style type="text/css">
#delobs {
    left:650px;
    margin:0;
    padding:10px;
    position:absolute;
    top:50%;
    width:650px;
    background-color: #ffffff;
    border: solid #000 1px;
}
</style>
<?php
$coluns = array(
    'Ação',
    'ID',
    'S',
    'Administradora',
    'Atividade',
    'Classe',
    'Inicio',
    'Fim',
    'Locador',
    'Locatario',
    'Valor',
    'Status'
    );
$td     = array(
    'nowrap',
    'nowrap class="r"',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap'
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'firt'));

$lambda = function($value,&$data){
        if($data[11] == "F"){
            echo "\t<td nowrap>",
                    '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>',
                 "</td>\n";   
        }
        if($data[11] == "C"){
            echo "\t<td nowrap>",
                    '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs</span>',
                 "</td>\n";   
        }
        if($data[11] == "A"){
            echo "\t<td nowrap>",
                    '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                    '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Deletar</span>',
                 "</td>\n";   
        }
    };
    
$this->ViewIndex('setFuncEdit',$lambda); 

foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getId() .'/'. $entity->getCodAno(),
        substr($entity->getSeguradora(),0,1),
        $entity->getAdministradora(),
        $entity->getAtividade(),
        $entity->getTaxa()->getClasse(),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->floatToStr('premioTotal'),
        $entity->getStatus(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
    <input type="hidden" name="renovacao" id="renovacao">
<div id="delobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoNaoFechou">Motivo do não fechamento.</label>
                    <textarea name="motivoNaoFechou" id="motivoNaoFechou" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir()"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:deleltar();"><i class="icon-trash"></i>Finalizar!</a>
            </td>
        </tr>
    </table>
</div> 
</form> 
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    } 
    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    }
    function getLogs(id){
        document.getElementById('id2').value = id ;
        document.getElementById('renovacao').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'logs','action'=>'logRenovacao')); ?>";
        envia(tar,id);        
    }
    function del(id){
        var motivo = document.getElementById('delobs');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar esta renovação?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;
    }  
    function desistir(){
        document.getElementById('delobs').style.display='none';
        document.getElementById('id2').value = '' ;
    }
    function deleltar(){
        var id = document.getElementById('id2').value;
        var obs = document.getElementById('motivoNaoFechou').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
        }
        if(id == '')return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        envia(tar,id);        
    }
    document.getElementById('delobs').style.display = 'none';
    
    $(document).ready(function(){
        var y_fixo = 500 + $("#delobs").offset().top;
        $(window).scroll(function () {
            $("#delobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
        });
    });
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>