<h1>Lista de Renovações</h1>
<br />
<style type="text/css">
#delobs {
    left:650px;
    margin:0;
    padding:10px;
    position:absolute;
    top:50%;
    width:650px;
    background-color: #ffffff;
    border: solid #000 1px;
}
</style>
<?php
echo '<form name="form" id="form" method="POST">';

$coluns = array(
    'ID<br><label class="checkbox" onClick="setCheckbox()"><input type="checkbox" id="CheckTodos" value="">Todos</label>',
    'Seguradora',
    'Administradora',
    'Atividade',
    'Ref Imovél',
    'Inicio',
    'Fim',
    'Locador',
    'Locatario',
    'Valor',
    'Status',
    'Ação'
    );
$td     = array(
    'nowrap class="r"',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap'
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));


$lambda = function($value,&$data){
        if($data[10] == "F"){
            echo "\t<td nowrap>",
                    '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>',
                 "</td>\n";   
        }
        if($data[10] == "A"){
            echo "\t<td nowrap>",
                    '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                    '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Deletar</span>',
                 "</td>\n";   
        }
    };
    
$this->ViewIndex('setFuncEdit',$lambda); 


foreach($this->data as $entity){ 
    $linha = array(
        '<label class="checkbox"><input type="checkbox" name="Checkeds[]" value="'. $entity->getId() .'">'. $entity->getId() .'/'. $entity->getCodAno() .'</label>',
        $entity->getSeguradora(),
        $entity->getAdministradora(),
        $entity->getAtividade(),
        $entity->getRefImovel(),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->floatToStr('premioTotal'),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');

?>
<div align='center'><input type="submit" name="fecharSel" id="fecharSel" class="btn-success" value="Fechar Selecionados" onclick="return fecharSelecionados()"></div>
<br />
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
<div id="delobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoNaoFechou">Motivo do não fechamento.</label>
                    <textarea name="motivoNaoFechou" id="motivoNaoFechou" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir()"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:deleltar();"><i class="icon-trash"></i>Finalizar!</a>
            </td>
        </tr>
    </table>
</div>    
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }
    function del(id){
        var motivo = document.getElementById('delobs');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar este orçamento?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;
    }  
    function desistir(){
        document.getElementById('delobs').style.display='none';
        document.getElementById('id2').value = '' ;
    }
    function deleltar(){
        var id = document.getElementById('id2').value;
        var obs = document.getElementById('motivoNaoFechou').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
        }
        if(id == '')return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        envia(tar,id);        
    }
    function setCheckbox(){
        var todos = document.getElementById('CheckTodos');
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            elems[i].checked = todos.checked;
        }
    }
    function fecharSelecionados(){
        //Verificar se algum orcamento foi marcado
        var aux = false;
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            if(elems[i].checked){
                aux = true;
                break;
            }
        }
        if(!aux){
            alert("Nenhum registro foi selecionado!!");
            return false;
        }
    
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'fecharSeguros')); ?>";
        envia(tar,'novo'); 
        return false;
    }
    document.getElementById('delobs').style.display = 'none';
    
    $(document).ready(function(){
        var y_fixo = 500 + $("#delobs").offset().top;
        $(window).scroll(function () {
            $("#delobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
        });
    });
</script>
