CREATE TABLE taxaAjuste (id INT AUTO_INCREMENT NOT NULL, classe_id INT DEFAULT NULL, administradoras_id INT DEFAULT NULL, seguradora_id INT DEFAULT NULL, inicio DATETIME NOT NULL, fim DATETIME DEFAULT NULL, status VARCHAR(10) DEFAULT NULL, validade VARCHAR(255) NOT NULL, ocupacao VARCHAR(2) NOT NULL, cont_ele NUMERIC(10, 4) DEFAULT '0' NOT NULL, conteudo NUMERIC(10, 4) DEFAULT '0' NOT NULL, eletrico NUMERIC(10, 4) DEFAULT '0' NOT NULL, sem_cont_ele NUMERIC(10, 4) DEFAULT '0' NOT NULL, com_eletrico NUMERIC(10, 4) DEFAULT '0' NOT NULL, sem_eletrico NUMERIC(10, 4) DEFAULT '0' NOT NULL, unica NUMERIC(10, 4) DEFAULT '0' NOT NULL, INDEX IDX_6E1F0CA08F5EA509 (classe_id), INDEX IDX_6E1F0CA02AEE976D (administradoras_id), INDEX IDX_6E1F0CA0CF32153 (seguradora_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE taxaAjuste ADD CONSTRAINT FK_6E1F0CA08F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id);
ALTER TABLE taxaAjuste ADD CONSTRAINT FK_6E1F0CA02AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
ALTER TABLE taxaAjuste ADD CONSTRAINT FK_6E1F0CA0CF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE orcamento DROP FOREIGN KEY FK_4B1DD46D81FFB11;
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46DC93F3536 FOREIGN KEY (locatario_id) REFERENCES locatario (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D4480E84F FOREIGN KEY (imovel_id) REFERENCES imovel (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D95DBD0F3 FOREIGN KEY (taxa_id) REFERENCES taxa (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46DA22D979B FOREIGN KEY (atividade_id) REFERENCES atividade (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46DCF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D2AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D67B3B43D FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46DA901C7E3 FOREIGN KEY (multiplos_minimos_id) REFERENCES multiplos_minimos (id_multiplos);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46DEEF4D318 FOREIGN KEY (comissao_id) REFERENCES comissao (id);
CREATE INDEX IDX_4B1DD46DEEF4D318 ON orcamento (comissao_id);
DROP INDEX fk_fechados_copy1_locador1 ON orcamento;
CREATE INDEX IDX_4B1DD46D81FFB11 ON orcamento (locador_id);
DROP INDEX fk_fechados_copy1_locatario1 ON orcamento;
CREATE INDEX IDX_4B1DD46DC93F3536 ON orcamento (locatario_id);
DROP INDEX fk_fechados_copy1_imovel1 ON orcamento;
CREATE INDEX IDX_4B1DD46D4480E84F ON orcamento (imovel_id);
DROP INDEX fk_fechados_copy1_taxa1 ON orcamento;
CREATE INDEX IDX_4B1DD46D95DBD0F3 ON orcamento (taxa_id);
DROP INDEX fk_fechados_copy1_atividade1 ON orcamento;
CREATE INDEX IDX_4B1DD46DA22D979B ON orcamento (atividade_id);
DROP INDEX fk_fechados_copy1_seguradora1 ON orcamento;
CREATE INDEX IDX_4B1DD46DCF32153 ON orcamento (seguradora_id);
DROP INDEX fk_fechados_copy1_administradoras1 ON orcamento;
CREATE INDEX IDX_4B1DD46D2AEE976D ON orcamento (administradoras_id);
DROP INDEX fk_orcamento_users1 ON orcamento;
CREATE INDEX IDX_4B1DD46D67B3B43D ON orcamento (users_id);
DROP INDEX fk_orcamento_multiplos_minimos1 ON orcamento;
CREATE INDEX IDX_4B1DD46DA901C7E3 ON orcamento (multiplos_minimos_id);
ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D81FFB11 FOREIGN KEY (locador_id) REFERENCES locador (id);
DROP INDEX atividade ON atividade;
DROP INDEX ocupacao ON atividade;
ALTER TABLE atividade CHANGE cod_seguradora cod_seguradora VARCHAR(45) NOT NULL, CHANGE ocupacao ocupacao VARCHAR(45) NOT NULL, CHANGE user_id_criado user_id_criado INT NOT NULL, CHANGE criado_em criado_em DATETIME NOT NULL, CHANGE status status VARCHAR(10) NOT NULL, CHANGE danos_eletricos danos_eletricos VARCHAR(1) NOT NULL, CHANGE equip_eletro equip_eletro VARCHAR(1) NOT NULL, CHANGE vendaval_fumaca vendaval_fumaca VARCHAR(1) NOT NULL, CHANGE basica basica VARCHAR(10) NOT NULL, CHANGE roubo roubo VARCHAR(10) NOT NULL, CHANGE seguradora_id seguradora_id INT DEFAULT NULL;
DROP INDEX index_key ON parametro_sis;
ALTER TABLE imovel DROP FOREIGN KEY fk_imovel_enderecos1;
ALTER TABLE imovel DROP FOREIGN KEY fk_imovel_locador1;
DROP INDEX index_cep ON imovel;
DROP INDEX index_rua ON imovel;
DROP INDEX index_rua_num_bl_apt ON imovel;
DROP INDEX index_ref_imovel ON imovel;
ALTER TABLE imovel DROP FOREIGN KEY fk_imovel_enderecos1;
ALTER TABLE imovel DROP FOREIGN KEY fk_imovel_locador1;
ALTER TABLE imovel CHANGE enderecos_id enderecos_id INT DEFAULT NULL, CHANGE locador_id locador_id INT DEFAULT NULL, CHANGE atividade_id atividade_id INT DEFAULT NULL, CHANGE locatario_id locatario_id INT DEFAULT NULL, CHANGE vlr_aluguel vlr_aluguel NUMERIC(10, 0) DEFAULT NULL, CHANGE compl compl LONGTEXT NOT NULL;
ALTER TABLE imovel ADD CONSTRAINT FK_902C0DEBA22D979B FOREIGN KEY (atividade_id) REFERENCES atividade (id);
ALTER TABLE imovel ADD CONSTRAINT FK_902C0DEB450D7B3F FOREIGN KEY (enderecos_id) REFERENCES enderecos (id);
ALTER TABLE imovel ADD CONSTRAINT FK_902C0DEB81FFB11 FOREIGN KEY (locador_id) REFERENCES locador (id);
ALTER TABLE imovel ADD CONSTRAINT FK_902C0DEBC93F3536 FOREIGN KEY (locatario_id) REFERENCES locatario (id);
CREATE INDEX IDX_902C0DEBC93F3536 ON imovel (locatario_id);
DROP INDEX fk_imovel_atividade ON imovel;
CREATE INDEX IDX_902C0DEBA22D979B ON imovel (atividade_id);
DROP INDEX fk_imovel_enderecos1 ON imovel;
CREATE INDEX IDX_902C0DEB450D7B3F ON imovel (enderecos_id);
DROP INDEX fk_imovel_locador1 ON imovel;
CREATE INDEX IDX_902C0DEB81FFB11 ON imovel (locador_id);
ALTER TABLE imovel ADD CONSTRAINT fk_imovel_enderecos1 FOREIGN KEY (enderecos_id) REFERENCES enderecos (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE imovel ADD CONSTRAINT fk_imovel_locador1 FOREIGN KEY (locador_id) REFERENCES locador (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE logs DROP INDEX fk_logs_users1, ADD UNIQUE INDEX UNIQ_F08FC65C67B3B43D (users_id);
ALTER TABLE logs DROP FOREIGN KEY fk_logs_users1;
DROP INDEX table_index ON logs;
DROP INDEX controller_index ON logs;
DROP INDEX table_action_index ON logs;
DROP INDEX user_index ON logs;
DROP INDEX data_table_index ON logs;
ALTER TABLE logs CHANGE users_id users_id INT DEFAULT NULL, CHANGE tabela tabela VARCHAR(30) NOT NULL, CHANGE controller controller VARCHAR(30) NOT NULL, CHANGE action action VARCHAR(30) NOT NULL, CHANGE ip ip VARCHAR(20) NOT NULL;
ALTER TABLE logs ADD CONSTRAINT FK_F08FC65C67B3B43D FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE enderecos CHANGE rua rua LONGTEXT NOT NULL, CHANGE compl compl LONGTEXT NOT NULL, CHANGE cep cep LONGTEXT NOT NULL, CHANGE user_id_alterado user_id_alterado INT NOT NULL, CHANGE alterado_em alterado_em DATETIME NOT NULL, CHANGE bairros_id bairros_id INT DEFAULT NULL, CHANGE cidades_id cidades_id INT DEFAULT NULL, CHANGE estados_id estados_id INT DEFAULT NULL, CHANGE paises_id paises_id INT DEFAULT NULL;
ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA74D10C48 FOREIGN KEY (bairros_id) REFERENCES bairros (id);
ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA72C7AFCB FOREIGN KEY (cidades_id) REFERENCES cidades (id);
ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA703C3EE9 FOREIGN KEY (estados_id) REFERENCES estados (id);
ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA282BEA6A FOREIGN KEY (paises_id) REFERENCES paises (id);
DROP INDEX fk_enderecos_bairros1 ON enderecos;
CREATE INDEX IDX_FC4E02DA74D10C48 ON enderecos (bairros_id);
DROP INDEX fk_enderecos_cidades1 ON enderecos;
CREATE INDEX IDX_FC4E02DA72C7AFCB ON enderecos (cidades_id);
DROP INDEX fk_enderecos_estados1 ON enderecos;
CREATE INDEX IDX_FC4E02DA703C3EE9 ON enderecos (estados_id);
DROP INDEX fk_enderecos_paises1 ON enderecos;
CREATE INDEX IDX_FC4E02DA282BEA6A ON enderecos (paises_id);
ALTER TABLE log_renovacao DROP INDEX index_user, ADD UNIQUE INDEX UNIQ_8A0C91C449C09C05 (user_id_criado);
ALTER TABLE log_renovacao DROP INDEX fk_log_renovacao_renovacao1, ADD UNIQUE INDEX UNIQ_8A0C91C4495A9EF0 (renovacao_id);
DROP INDEX index_data ON log_renovacao;
DROP INDEX index_user_data ON log_renovacao;
ALTER TABLE log_renovacao CHANGE controller controller VARCHAR(30) DEFAULT NULL, CHANGE action action VARCHAR(30) DEFAULT NULL, CHANGE ip ip VARCHAR(20) NOT NULL, CHANGE renovacao_id renovacao_id INT DEFAULT NULL;
ALTER TABLE log_renovacao ADD CONSTRAINT FK_8A0C91C449C09C05 FOREIGN KEY (user_id_criado) REFERENCES users (id);
ALTER TABLE log_renovacao ADD CONSTRAINT FK_8A0C91C4495A9EF0 FOREIGN KEY (renovacao_id) REFERENCES orcamento (id);
ALTER TABLE log_fechados DROP INDEX index_user, ADD UNIQUE INDEX UNIQ_4743BC449C09C05 (user_id_criado);
DROP INDEX index_data ON log_fechados;
DROP INDEX index_user_data ON log_fechados;
ALTER TABLE log_fechados CHANGE controller controller VARCHAR(30) DEFAULT NULL, CHANGE action action VARCHAR(30) DEFAULT NULL, CHANGE ip ip VARCHAR(20) NOT NULL, CHANGE fechados_id fechados_id INT DEFAULT NULL;
ALTER TABLE log_fechados ADD CONSTRAINT FK_4743BC449C09C05 FOREIGN KEY (user_id_criado) REFERENCES users (id);
ALTER TABLE log_fechados ADD CONSTRAINT FK_4743BC4C784DD1D FOREIGN KEY (fechados_id) REFERENCES fechados (id);
DROP INDEX fk_log_fechados_fechados1 ON log_fechados;
CREATE INDEX IDX_4743BC4C784DD1D ON log_fechados (fechados_id);
ALTER TABLE taxa DROP INDEX fk_taxa_classe1, ADD UNIQUE INDEX UNIQ_515FEBF08F5EA509 (classe_id);
ALTER TABLE taxa DROP INDEX fk_taxa_seguradora1, ADD UNIQUE INDEX UNIQ_515FEBF0CF32153 (seguradora_id);
ALTER TABLE taxa DROP FOREIGN KEY fk_taxa_classe1;
ALTER TABLE taxa DROP FOREIGN KEY fk_taxa_seguradora1;
ALTER TABLE taxa CHANGE classe_id classe_id INT DEFAULT NULL, CHANGE status status VARCHAR(10) DEFAULT NULL, CHANGE incendio incendio NUMERIC(20, 8) DEFAULT '0' NOT NULL, CHANGE incendio_conteudo incendio_conteudo VARCHAR(255) DEFAULT '0' NOT NULL, CHANGE aluguel aluguel NUMERIC(20, 8) DEFAULT '0' NOT NULL, CHANGE eletrico eletrico NUMERIC(20, 8) DEFAULT '0' NOT NULL, CHANGE vendaval vendaval NUMERIC(20, 8) DEFAULT '0' NOT NULL, CHANGE validade validade VARCHAR(10) NOT NULL, CHANGE ocupacao ocupacao VARCHAR(10) NOT NULL, CHANGE comissao comissao NUMERIC(10, 4) DEFAULT '0' NOT NULL, CHANGE seq seq VARCHAR(1) DEFAULT NULL, CHANGE tipo_cobertura tipo_cobertura VARCHAR(2) NOT NULL;
ALTER TABLE taxa ADD CONSTRAINT FK_515FEBF08F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id);
ALTER TABLE taxa ADD CONSTRAINT FK_515FEBF0CF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE estados CHANGE nome nome LONGTEXT NOT NULL, CHANGE sigla sigla LONGTEXT NOT NULL;
DROP INDEX adm_mes_ano ON log_fatura_col;
ALTER TABLE log_fatura_col CHANGE criado_em criado_em DATETIME DEFAULT NULL;
ALTER TABLE classe_atividade DROP FOREIGN KEY fk_classe_atividade_atividade1;
ALTER TABLE classe_atividade DROP FOREIGN KEY fk_classe_atividade_classe_taxas1;
ALTER TABLE classe_atividade DROP FOREIGN KEY fk_classe_atividade_atividade1;
ALTER TABLE classe_atividade DROP FOREIGN KEY fk_classe_atividade_classe_taxas1;
ALTER TABLE classe_atividade CHANGE atividade_id atividade_id INT DEFAULT NULL, CHANGE classe_taxas_id classe_taxas_id INT DEFAULT NULL, CHANGE status status VARCHAR(10) NOT NULL, CHANGE cod_old cod_old INT DEFAULT NULL, CHANGE codcia_old codcia_old INT DEFAULT NULL, CHANGE seq seq VARCHAR(1) DEFAULT NULL;
ALTER TABLE classe_atividade ADD CONSTRAINT FK_223056E5F99E0DFD FOREIGN KEY (classe_taxas_id) REFERENCES classe (id);
ALTER TABLE classe_atividade ADD CONSTRAINT FK_223056E5A22D979B FOREIGN KEY (atividade_id) REFERENCES atividade (id);
DROP INDEX fk_classe_atividade_classe_taxas1 ON classe_atividade;
CREATE INDEX IDX_223056E5F99E0DFD ON classe_atividade (classe_taxas_id);
DROP INDEX fk_classe_atividade_atividade1 ON classe_atividade;
CREATE INDEX IDX_223056E5A22D979B ON classe_atividade (atividade_id);
ALTER TABLE classe_atividade ADD CONSTRAINT fk_classe_atividade_atividade1 FOREIGN KEY (atividade_id) REFERENCES atividade (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE classe_atividade ADD CONSTRAINT fk_classe_atividade_classe_taxas1 FOREIGN KEY (classe_taxas_id) REFERENCES classe (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE log_orcamento DROP INDEX fk_log_f_copy1_orcamento1, ADD UNIQUE INDEX UNIQ_5D1F48E3A01CF1CA (orcamento_id);
ALTER TABLE log_orcamento DROP INDEX index_user, ADD UNIQUE INDEX UNIQ_5D1F48E349C09C05 (user_id_criado);
DROP INDEX index_data ON log_orcamento;
DROP INDEX index_user_data ON log_orcamento;
ALTER TABLE log_orcamento CHANGE controller controller VARCHAR(30) DEFAULT NULL, CHANGE action action VARCHAR(30) DEFAULT NULL, CHANGE ip ip VARCHAR(20) NOT NULL, CHANGE orcamento_id orcamento_id INT DEFAULT NULL;
ALTER TABLE log_orcamento ADD CONSTRAINT FK_5D1F48E349C09C05 FOREIGN KEY (user_id_criado) REFERENCES users (id);
ALTER TABLE log_orcamento ADD CONSTRAINT FK_5D1F48E3A01CF1CA FOREIGN KEY (orcamento_id) REFERENCES orcamento (id);
ALTER TABLE administradoras DROP INDEX fk_administradoras_enderecos1, ADD UNIQUE INDEX UNIQ_DE106EE2450D7B3F (enderecos_id);
ALTER TABLE administradoras DROP INDEX fk_administradoras_seguradora1, ADD UNIQUE INDEX UNIQ_DE106EE2CF32153 (seguradora_id);
ALTER TABLE administradoras DROP FOREIGN KEY fk_administradoras_enderecos1;
ALTER TABLE administradoras DROP FOREIGN KEY fk_administradoras_seguradora1;
DROP INDEX cnpj_UNIQUE ON administradoras;
DROP INDEX codigo_col ON administradoras;
ALTER TABLE administradoras CHANGE seguradora_id seguradora_id INT DEFAULT NULL, CHANGE nome nome LONGTEXT NOT NULL, CHANGE codigo_col codigo_col INT NOT NULL, CHANGE apelido apelido LONGTEXT NOT NULL, CHANGE cnpj cnpj LONGTEXT NOT NULL, CHANGE tel tel LONGTEXT NOT NULL, CHANGE email email LONGTEXT NOT NULL, CHANGE status status LONGTEXT NOT NULL, CHANGE forma_pagto forma_pagto VARCHAR(10) NOT NULL, CHANGE validade validade VARCHAR(255) NOT NULL, CHANGE tipo_cobertura tipo_cobertura VARCHAR(2) NOT NULL, CHANGE user_id_alterado user_id_alterado INT NOT NULL, CHANGE alterado_em alterado_em DATETIME NOT NULL, CHANGE assist24 assist24 LONGTEXT NOT NULL, CHANGE tipo_cobertura_res tipo_cobertura_res VARCHAR(2) NOT NULL, CHANGE prop_pag prop_pag VARCHAR(2) NOT NULL;
ALTER TABLE administradoras ADD CONSTRAINT FK_DE106EE2450D7B3F FOREIGN KEY (enderecos_id) REFERENCES enderecos (id);
ALTER TABLE administradoras ADD CONSTRAINT FK_DE106EE2CF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE cidades CHANGE nome nome LONGTEXT NOT NULL;
DROP INDEX index_status ON renovacao;
DROP INDEX index_criado_em ON renovacao;
ALTER TABLE renovacao CHANGE valor_aluguel valor_aluguel NUMERIC(10, 0) NOT NULL, CHANGE incendio incendio NUMERIC(10, 0) NOT NULL, CHANGE conteudo conteudo NUMERIC(10, 0) DEFAULT NULL, CHANGE aluguel aluguel NUMERIC(10, 0) NOT NULL, CHANGE eletrico eletrico NUMERIC(10, 0) NOT NULL, CHANGE vendaval vendaval NUMERIC(10, 0) NOT NULL, CHANGE premio_liquido premio_liquido NUMERIC(10, 0) NOT NULL, CHANGE premio premio NUMERIC(10, 0) NOT NULL, CHANGE premio_total premio_total NUMERIC(10, 0) NOT NULL, CHANGE gerado gerado VARCHAR(1) DEFAULT NULL, CHANGE comissao comissao NUMERIC(10, 0) DEFAULT NULL, CHANGE locador_id locador_id INT DEFAULT NULL, CHANGE locatario_id locatario_id INT DEFAULT NULL, CHANGE taxa_id taxa_id INT DEFAULT NULL, CHANGE atividade_id atividade_id INT DEFAULT NULL, CHANGE seguradora_id seguradora_id INT DEFAULT NULL, CHANGE administradoras_id administradoras_id INT DEFAULT NULL, CHANGE users_id users_id INT DEFAULT NULL, CHANGE multiplos_minimos_id multiplos_minimos_id INT DEFAULT NULL, CHANGE fechado_id fechado_id INT NOT NULL, CHANGE validade validade VARCHAR(10) DEFAULT NULL, CHANGE ocupacao ocupacao VARCHAR(2) DEFAULT NULL, CHANGE taxa_iof taxa_iof NUMERIC(10, 0) NOT NULL, CHANGE cob_incendio cob_incendio NUMERIC(10, 0) NOT NULL, CHANGE cob_conteudo cob_conteudo NUMERIC(10, 0) NOT NULL, CHANGE cob_aluguel cob_aluguel NUMERIC(10, 0) NOT NULL, CHANGE cob_eletrico cob_eletrico NUMERIC(10, 0) NOT NULL, CHANGE cob_vendaval cob_vendaval NUMERIC(10, 0) NOT NULL, CHANGE comissao_id comissao_id INT DEFAULT NULL, CHANGE mensal_seq mensal_seq INT DEFAULT NULL;
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4A81FFB11 FOREIGN KEY (locador_id) REFERENCES locador (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4AC93F3536 FOREIGN KEY (locatario_id) REFERENCES locatario (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4A4480E84F FOREIGN KEY (imovel_id) REFERENCES imovel (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4A95DBD0F3 FOREIGN KEY (taxa_id) REFERENCES taxa (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4AA22D979B FOREIGN KEY (atividade_id) REFERENCES atividade (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4ACF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4A2AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4A67B3B43D FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4AA901C7E3 FOREIGN KEY (multiplos_minimos_id) REFERENCES multiplos_minimos (id_multiplos);
ALTER TABLE renovacao ADD CONSTRAINT FK_9C0E0D4AEEF4D318 FOREIGN KEY (comissao_id) REFERENCES comissao (id);
CREATE UNIQUE INDEX UNIQ_9C0E0D4AEEF4D318 ON renovacao (comissao_id);
DROP INDEX fk_fechados_copy1_locador1 ON renovacao;
CREATE INDEX IDX_9C0E0D4A81FFB11 ON renovacao (locador_id);
DROP INDEX fk_fechados_copy1_locatario1 ON renovacao;
CREATE INDEX IDX_9C0E0D4AC93F3536 ON renovacao (locatario_id);
DROP INDEX fk_fechados_copy1_imovel1 ON renovacao;
CREATE INDEX IDX_9C0E0D4A4480E84F ON renovacao (imovel_id);
DROP INDEX fk_fechados_copy1_taxa1 ON renovacao;
CREATE INDEX IDX_9C0E0D4A95DBD0F3 ON renovacao (taxa_id);
DROP INDEX fk_fechados_copy1_atividade1 ON renovacao;
CREATE INDEX IDX_9C0E0D4AA22D979B ON renovacao (atividade_id);
DROP INDEX fk_fechados_copy1_seguradora1 ON renovacao;
CREATE INDEX IDX_9C0E0D4ACF32153 ON renovacao (seguradora_id);
DROP INDEX fk_fechados_copy1_administradoras1 ON renovacao;
CREATE INDEX IDX_9C0E0D4A2AEE976D ON renovacao (administradoras_id);
DROP INDEX fk_orcamento_users1 ON renovacao;
CREATE INDEX IDX_9C0E0D4A67B3B43D ON renovacao (users_id);
DROP INDEX fk_renovacao_multiplos_minimos1 ON renovacao;
CREATE INDEX IDX_9C0E0D4AA901C7E3 ON renovacao (multiplos_minimos_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_locador1, ADD UNIQUE INDEX UNIQ_6A27F01B81FFB11 (locador_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_locatario1, ADD UNIQUE INDEX UNIQ_6A27F01BC93F3536 (locatario_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_imovel1, ADD UNIQUE INDEX UNIQ_6A27F01B4480E84F (imovel_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_taxa1, ADD UNIQUE INDEX UNIQ_6A27F01B95DBD0F3 (taxa_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_atividade1, ADD UNIQUE INDEX UNIQ_6A27F01BA22D979B (atividade_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_seguradora1, ADD UNIQUE INDEX UNIQ_6A27F01BCF32153 (seguradora_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_administradoras1, ADD UNIQUE INDEX UNIQ_6A27F01B2AEE976D (administradoras_id);
ALTER TABLE fechados DROP INDEX fk_fechados_copy1_users1, ADD UNIQUE INDEX UNIQ_6A27F01B67B3B43D (users_id);
ALTER TABLE fechados DROP INDEX fk_fechados_multiplos_minimos1, ADD UNIQUE INDEX UNIQ_6A27F01BA901C7E3 (multiplos_minimos_id);
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_1;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_10;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_11;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_12;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_13;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_14;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_15;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_16;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_17;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_18;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_2;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_3;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_4;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_5;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_6;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_7;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_8;
ALTER TABLE fechados DROP FOREIGN KEY fechados_ibfk_9;
DROP INDEX index_comissao_inicio ON fechados;
DROP INDEX index_criado_em ON fechados;
ALTER TABLE fechados CHANGE locador_id locador_id INT DEFAULT NULL, CHANGE locatario_id locatario_id INT DEFAULT NULL, CHANGE valor_aluguel valor_aluguel NUMERIC(10, 0) NOT NULL, CHANGE incendio incendio NUMERIC(10, 0) NOT NULL, CHANGE conteudo conteudo NUMERIC(10, 0) DEFAULT NULL, CHANGE aluguel aluguel NUMERIC(10, 0) NOT NULL, CHANGE eletrico eletrico NUMERIC(10, 0) NOT NULL, CHANGE vendaval vendaval NUMERIC(10, 0) NOT NULL, CHANGE premio_liquido premio_liquido NUMERIC(10, 0) NOT NULL, CHANGE premio premio NUMERIC(10, 0) NOT NULL, CHANGE premio_total premio_total NUMERIC(10, 0) NOT NULL, CHANGE gerado gerado VARCHAR(1) DEFAULT NULL, CHANGE comissao comissao NUMERIC(10, 0) DEFAULT NULL, CHANGE taxa_id taxa_id INT DEFAULT NULL, CHANGE atividade_id atividade_id INT DEFAULT NULL, CHANGE seguradora_id seguradora_id INT DEFAULT NULL, CHANGE administradoras_id administradoras_id INT DEFAULT NULL, CHANGE users_id users_id INT DEFAULT NULL, CHANGE multiplos_minimos_id multiplos_minimos_id INT DEFAULT NULL, CHANGE validade validade VARCHAR(10) DEFAULT NULL, CHANGE ocupacao ocupacao VARCHAR(2) DEFAULT NULL, CHANGE taxa_iof taxa_iof NUMERIC(10, 0) NOT NULL, CHANGE cob_incendio cob_incendio NUMERIC(10, 0) NOT NULL, CHANGE cob_conteudo cob_conteudo NUMERIC(10, 0) NOT NULL, CHANGE cob_aluguel cob_aluguel NUMERIC(10, 0) NOT NULL, CHANGE cob_eletrico cob_eletrico NUMERIC(10, 0) NOT NULL, CHANGE cob_vendaval cob_vendaval NUMERIC(10, 0) NOT NULL, CHANGE comissao_id comissao_id INT DEFAULT NULL, CHANGE mensal_seq mensal_seq INT DEFAULT NULL, CHANGE assist24 assist24 LONGTEXT NOT NULL;
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01B81FFB11 FOREIGN KEY (locador_id) REFERENCES locador (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01BC93F3536 FOREIGN KEY (locatario_id) REFERENCES locatario (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01B4480E84F FOREIGN KEY (imovel_id) REFERENCES imovel (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01B95DBD0F3 FOREIGN KEY (taxa_id) REFERENCES taxa (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01BA22D979B FOREIGN KEY (atividade_id) REFERENCES atividade (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01BCF32153 FOREIGN KEY (seguradora_id) REFERENCES seguradora (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01B2AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01B67B3B43D FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01BA901C7E3 FOREIGN KEY (multiplos_minimos_id) REFERENCES multiplos_minimos (id_multiplos);
ALTER TABLE fechados ADD CONSTRAINT FK_6A27F01BEEF4D318 FOREIGN KEY (comissao_id) REFERENCES comissao (id);
CREATE UNIQUE INDEX UNIQ_6A27F01BEEF4D318 ON fechados (comissao_id);
ALTER TABLE bairros CHANGE nome nome LONGTEXT NOT NULL;
ALTER TABLE paises CHANGE nome nome LONGTEXT NOT NULL, CHANGE sigla sigla LONGTEXT NOT NULL, CHANGE codigo codigo LONGTEXT NOT NULL;
ALTER TABLE locatario DROP FOREIGN KEY fk_locatario_enderecos1;
DROP INDEX cpf_index ON locatario;
DROP INDEX nome_index ON locatario;
DROP INDEX cnpj_index ON locatario;
ALTER TABLE locatario DROP FOREIGN KEY fk_locatario_enderecos1;
ALTER TABLE locatario CHANGE nome nome VARCHAR(200) NOT NULL, CHANGE status status VARCHAR(10) NOT NULL;
ALTER TABLE locatario ADD CONSTRAINT FK_9DEC98FE450D7B3F FOREIGN KEY (enderecos_id) REFERENCES enderecos (id);
DROP INDEX fk_locatario_enderecos1 ON locatario;
CREATE INDEX IDX_9DEC98FE450D7B3F ON locatario (enderecos_id);
ALTER TABLE locatario ADD CONSTRAINT fk_locatario_enderecos1 FOREIGN KEY (enderecos_id) REFERENCES enderecos (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE seguradora DROP INDEX fk_seguradora_enderecos1, ADD UNIQUE INDEX UNIQ_BEB590EC450D7B3F (enderecos_id);
ALTER TABLE seguradora DROP FOREIGN KEY fk_seguradora_enderecos1;
ALTER TABLE seguradora CHANGE apelido apelido VARCHAR(45) DEFAULT NULL, CHANGE cnpj cnpj VARCHAR(45) NOT NULL, CHANGE status status VARCHAR(10) NOT NULL;
ALTER TABLE seguradora ADD CONSTRAINT FK_BEB590EC450D7B3F FOREIGN KEY (enderecos_id) REFERENCES enderecos (id);
ALTER TABLE locador DROP FOREIGN KEY fk_locador_administradoras1;
ALTER TABLE locador DROP FOREIGN KEY fk_locador_enderecos1;
ALTER TABLE locador DROP FOREIGN KEY fk_locador_administradoras1;
ALTER TABLE locador DROP FOREIGN KEY fk_locador_enderecos1;
ALTER TABLE locador CHANGE administradoras_id administradoras_id INT DEFAULT NULL, CHANGE tipo tipo VARCHAR(5) NOT NULL;
ALTER TABLE locador ADD CONSTRAINT FK_6660DD1F450D7B3F FOREIGN KEY (enderecos_id) REFERENCES enderecos (id);
ALTER TABLE locador ADD CONSTRAINT FK_6660DD1F2AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
DROP INDEX fk_locador_enderecos1 ON locador;
CREATE INDEX IDX_6660DD1F450D7B3F ON locador (enderecos_id);
DROP INDEX fk_locador_administradoras1 ON locador;
CREATE INDEX IDX_6660DD1F2AEE976D ON locador (administradoras_id);
ALTER TABLE locador ADD CONSTRAINT fk_locador_administradoras1 FOREIGN KEY (administradoras_id) REFERENCES administradoras (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE locador ADD CONSTRAINT fk_locador_enderecos1 FOREIGN KEY (enderecos_id) REFERENCES enderecos (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE comissao DROP FOREIGN KEY fk_comissao_administradoras1;
DROP INDEX index_inicio ON comissao;
DROP INDEX index_fim ON comissao;
ALTER TABLE comissao DROP FOREIGN KEY fk_comissao_administradoras1;
ALTER TABLE comissao CHANGE administradoras_id administradoras_id INT DEFAULT NULL, CHANGE Comissao Comissao NUMERIC(10, 0) NOT NULL, CHANGE status status VARCHAR(10) DEFAULT NULL, CHANGE mult_incendio mult_incendio INT DEFAULT NULL, CHANGE mult_conteudo mult_conteudo INT DEFAULT NULL, CHANGE mult_aluguel mult_aluguel INT NOT NULL, CHANGE mult_eletrico mult_eletrico INT DEFAULT NULL, CHANGE mult_vendaval mult_vendaval INT DEFAULT NULL, CHANGE comissao_res comissao_res NUMERIC(10, 0) NOT NULL;
ALTER TABLE comissao ADD CONSTRAINT FK_E826B2D12AEE976D FOREIGN KEY (administradoras_id) REFERENCES administradoras (id);
DROP INDEX fk_comissao_administradoras1 ON comissao;
CREATE INDEX IDX_E826B2D12AEE976D ON comissao (administradoras_id);
ALTER TABLE comissao ADD CONSTRAINT fk_comissao_administradoras1 FOREIGN KEY (administradoras_id) REFERENCES administradoras (id) ON UPDATE CASCADE ON DELETE CASCADE;
