<h1>Classes</h1>
<br />

<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'classes','action'=>'new')); ?>">Novo</a>
</p>

<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
    <tr>
        <th>ID</th>
        <th>Codigo</th>
        <th>Descrição</th>
        <th>Seguradora</th>
        <th>Ação</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getCod(); ?></td>
        <td><?php echo $entity->getDescricao(); ?></td>
        <td><?php echo $entity->getSeguradora(); ?></td>
        <td>
            <a href="<?php echo $this->url('livraria-admin-interna',
                    array('controller'=>'classes','action'=>'edit','id'=>$entity->getId())); ?>">Editar</a>
            <a href="<?php echo $this->url('livraria-admin-interna',
                    array('controller'=>'classes','action'=>'delete','id'=>$entity->getId())); ?>">Deletar</a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>