<h3>Nova Estados</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'estados','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('sigla'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>