<?php 
if($this->resultSet){
    echo "ok|s|";
    $cont = 0;
    foreach($this->resultSet as $entity){
        if($cont > 0)echo "|s|";
        $cont++;
        if($this->subOpcao ==''){
            echo $entity->getId(), "|c|"; 
            echo $entity->getNome(), "|c|"; 
            echo $entity->getId(), "|c|"; 
            echo $entity->getNome(), "|c|"; 
            echo $entity->getCpf(), $entity->getCnpj(), "|c|"; 
        }
        if($this->subOpcao =='tipo2'){
            echo $entity->getId(), "|c|"; 
            echo $entity->getNome(), "|c|"; 
            echo $entity->getTipo(), "|c|"; 
            echo $entity->getCpf(), $entity->getCnpj(), "|c|"; 
            echo $entity->getId(), "|c|"; 
            echo $entity->getNome(), "|c|"; 
            echo $entity->getTipo(), "|c|"; 
            echo $entity->getCpf(), $entity->getCnpj(), "|c|"; 
        }
    }
}else
    echo "vazio|s|";