<h1>Locatarios</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Locatario</span></p>
<?php

    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp'], 'hidden'),
                $this->FormDefault(['nome'], 'text'),
            "</td><td>\r",
                $this->FormDefault(['cpfOuCnpj'], 'radio'),
            "</td><td>\r",
                $this->FormDefault(['documento'], 'text'),
            "</td><td style='width:40%; vertical-align: middle;'>\r",
                $this->FormDefault(['enviar'], 'submitOnly'),
            "</td>\r",
        $this->FormDefault([],'fim');
    }
    
$coluns = array('ID','Nome','Tipo','Cpf ou Cnpj','Telefone','Email','Status','Ação');
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getNome(),
        $entity->getTipo(),
        $entity->getCpf() . $entity->getCnpj() ,
        $entity->getTel(),
        $entity->getEmail(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'index')); ?>";
        envia(tar,'buscar',formName);
    }  
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>