<h3>Editando administradora</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin-interna',array('controller'=>'administradoras','action'=>'edit')));

$form->prepare();
echo $this->form()->openTag($form);

echo "<fieldset>";
echo "  <legend>Dados Basicos:</legend>";
echo $this->formHidden($form->get('id')),"\r";
echo "<table style='width : 100% ;'>";
echo "<tr>";
echo "<td>";
echo $this->formRow($form->get('nome')),"\r";
echo $this->formRow($form->get('tel')),"\r";
echo "</td><td>";
echo $this->formRow($form->get('apelido')),"\r";
echo $this->formRow($form->get('email')),"\r";
echo "</td><td>";
echo $this->formRow($form->get('cnpj')),"\r";
echo $this->formRow($form->get('status')),"\r";
echo "</td></tr>";
echo "</table>";
echo " </fieldset>";

require "/var/www/zf2vv/module/Livraria/view/livraria-admin/enderecos/formEnderecoInc.php";

echo "<div align='center'>";
echo $this->formSubmit($form->get('submit'));
echo "</div>";

echo $this->form()->closeTag();
?>