<br /><h1>Administradoras</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Administradora</span></p>
<?php

    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['administradora', 'ajaxStatus', 'subOpcao','autoComp'], 'hidden'),
                $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'iconeLine'),
                "</td>\r",
        $this->FormDefault([],'fim');
    }
    
$coluns = array(
    'ID',
    'Nome',
    'Apelido',
    'CNPJ',
    'Tel',
    'Email',
    'Status',
    'Ação'
);
$td     = [];
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    if($entity->getId() == 1)continue; //pula o id 1 ele é uma referencia vazia
    $linha = array(
        $entity->getId(),
        $entity->getNome(),
        $entity->getApelido(),
        $entity->getCnpj(),
        $entity->getTel(),
        $entity->getEmail(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    
    var tar = '<?php echo $this->url($this->matchedRouteName,$this->params); ?>';
    var formName = '<?php echo $this->formName ?>';
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscaAdministradora()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }
    function buscaAdministradora(){
        envia(tar,'buscar',formName);
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>