<h3>Selectionar arquivo a ser importado da Lello.</h3>

<p><span class="add-on hand" onClick="voltar();"><i class="icon-backward"></i>Voltar</span></p>
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'importar','action'=>'upload')));

$form->prepare();

echo 
$this->FormDefault(['legend' => 'Selecionar Arquivos', 'hidden' => 'id'],'inicio',$this, $form),
    $this->FormDefault(['subOpcao' => 'hidden']),
        "\n<td>",
            $this->formRow($form->get('content')),
        "</td>\n",
        
$this->FormDefault(['submit' => 'importar'],'fim');

?>
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    var tar = '<?php echo $this->url($this->matchedRouteName,$this->params); ?>';
    var formName = '<?php echo $this->formName ?>';
    function voltar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'index','action'=>'importar')); ?>";
        envia(tar,'',formName);
    }
    function importarFile(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'upload')); ?>";
        envia(tar,'',formName);
        return false;
    }
</script>