<?php
//Montar tabela para exibição xls.
$tabela_dados = "\n<table cellpadding='0' cellspacing='0' border='0' id='table'>\n<thead>\n<tr>\n" ;

if(empty($this->data)){
    $tabela_dados .= '<tr><td>Nenhum resultado foi encontrado!!!!</td></tr>';
}else{
    $qtd    = sizeof($this->data[0]);
    $coluns = $this->data[0];
    //Montar cabeçalho
    foreach ($coluns as $value) {
        $tabela_dados .= "<th nowrap>" . $value . "</th>\n";
    }
    //Adicionando todas as colunas no vetor para exibição das linhas
    $tabela_dados .= "</tr>\n</thead>\n<tbody>\n";
    $cor = "";
}

foreach($this->data as $key => $value){
    if($key == 0){
        continue;
    }
    if(isset($value['result'])){
        if($value['result'][0] === TRUE){
            $tabela_dados .= '<tr><td colspan="' . $qtd . '" style="background:#B9FFB9">Gerou Orçamento de numero de ' . $value['result'][1] ;
        }else{
            $tabela_dados .= '<tr><td colspan="' . $qtd . '" style="background:#DA9694">Não importou lista de motivos Abaixo:<br>';
            foreach ($value['result'] as $resul) {
                $tabela_dados .= $resul . '<br />';
            }
        }
        $tabela_dados .= '</td></tr>'; 
        continue;
    }   
    // Decide cor da linha
    if($cor == "background:#EBF1DE;"){
        $cor = "";
    }else{
        $cor = "background:#EBF1DE;";
    } 
    $tabela_dados .= "<tr>\n" ;
    foreach ($value as $cel) {
        $align = "align='left'";
        //Colocar um traço para celula vazia
        if($cel == ""){
            $cel = "-";
            $align = "align='center'";
        }
        $tabela_dados .= "\t<td nowrap $align style='" . $cor . "'>" . $cel . "</td>\n" ;
    }
    $tabela_dados .= "</tr>\n" ;
}
$tabela_dados .= "</table>\n" ;
//Nome do arquivo
$filename = "ImportacaoLello_Resultado" . date('d-m-Y_H-i-s');
//XLS - exibe a tabela pronta em html para XLS
header("Content-Type:  application/vnd.ms-excel; charset=UTF-8; encoding=UTF-8");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header ("Content-Disposition: attachment; filename=\"".$filename.".xls\"" );
print(utf8_decode($tabela_dados));
