<h1>Multiplos e Minimos</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Novo Multiplos e Minimos</span></p>

<?php
$coluns = array('ID','Seguradora','Inicio','Fim','Mult Aluguel','Mult Conteudo','Mult Predio','Mult Eletrico','Mult Vendaval',
                'Min Aluguel','Min Conteudo','Min Predio','Min Eletrico','Min Vendaval','Status','Ação');
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getSeguradora(),
        $entity->getMultVigenciaInicio(),
        $entity->getMultVigenciaFim(),
        $entity->floatToStr('multAluguel'),
        $entity->floatToStr('multConteudo'),
        $entity->floatToStr('multPredio'),
        $entity->floatToStr('multEletrico'),
        $entity->floatToStr('multVendaval'),
        $entity->floatToStr('minAluguel'),
        $entity->floatToStr('minConteudo'),
        $entity->floatToStr('minPredio'),
        $entity->floatToStr('minEletrico'),
        $entity->floatToStr('minVendaval'),
        $entity->getMultStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>