<h1>Limites de Contratação</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Novo Limite de Contratação</span></p>

<?php
$coluns = array(
    'ID',
    'Seguradora',
    'Inicio',
    'Fim',
    /*
    'Mult Aluguel',
    'Mult Incendio',
    'Mult Conteudo',
    'Mult Eletrico',
    'Mult Vendaval',
     */
    'Min Aluguel',
    'Min Incendio',
    'Min Conteudo',
    'Min Eletrico',
    'Min Vendaval',
                
    'Max Aluguel',
    'Max Incendio',
    'Max Conteudo',
    'Max Eletrico',
    'Max Vendaval',
    'Status',
    'Ação'
    );
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getSeguradora(),
        $entity->getMultVigenciaInicio(),
        $entity->getMultVigenciaFim(),
        /*
        $entity->floatToStr('multAluguel'),
        $entity->floatToStr('multIncendio'),
        $entity->floatToStr('multConteudo'),
        $entity->floatToStr('multEletrico'),
        $entity->floatToStr('multVendaval'),
         */
        $entity->floatToStr('minAluguel'),
        $entity->floatToStr('minIncendio'),
        $entity->floatToStr('minConteudo'),
        $entity->floatToStr('minEletrico'),
        $entity->floatToStr('minVendaval'),
        $entity->floatToStr('maxAluguel'),
        $entity->floatToStr('maxIncendio'),
        $entity->floatToStr('maxConteudo'),
        $entity->floatToStr('maxEletrico'),
        $entity->floatToStr('maxVendaval'),
        $entity->getMultStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>