<style type="text/css" media="print">
    .F2 {
        font-size: 10pt;
    }    
    .F1 {
        font-size: 8pt;
    }
    .F8 {
        font-size: 6pt;
    }
</style>
<style>
    .F2 {
        font-size: 12pt;
    }    
    .F1 {
        font-size: 10pt;
    }
    .F8 {
        font-size: 8pt;
    }
    .Br {
        border-right:  #333 solid 1px ;
    }
    .Bl {
        border-left:   #333 solid 1px ;
    }
    .Bt {
        border-top:    #333 solid 1px ;
    }
    .Bb {
        border-bottom: #333 solid 1px ;
    }
</style>


<?  

$total    = 0;
$qtd      = 0;
$total2   = 0;
$qtd2     = 0;
$adm      = 0;
$tipo     = '';
$comissaoOld = '';
$comissao = '';
$ocupacaoOld = '';
$ocupacao = '';
$parcelaOld = '';
$parcela  = '';
$parc     = '';
$mesSel   = $this->date['mesFiltro'];
foreach($this->data as $ent): 
    // Verifica se trocou de adm e verifica se tem necessidade de finalizar tabela da adm anterior
    $admAtual = $ent->getAdministradora()->getId();
    if($adm != $admAtual):
        if($adm != 0):
        ?>
        <tr>
                <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
                <td class="Bl Bb Bt" align="center">Total</td>
                <td class="Bl Bb Bt" align="center" colspan="3"><? echo $qtd ?></td>
                <td class="Bl Bb Bt Br" align="right" colspan="2"><? echo number_format($total, 2, ',', '.') ?></td>
        </tr> 
        </table> 
        <br />
        <table class="Bt Bb"  style="width: 100% ;">
        <tr><th class="Bl Br" align="center">Observação: </th></tr>  
        <tr>  
                <td class="Bl Bb Bt Br F1" rowspan="3">Caso a somatória dos prêmios de cada forma de pagamento for inferior a R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão
        de apólice.</td>
        </tr>  
        </table> 
        <br />
        <?
            $qtd = 0;
            $total = 0;          
            $pagCss = ' class="quebra"';
            $parcelaOld = '';
        else:
            $pagCss = '';            
        endif;            
    ?>
<table style="width: 100% ;" <? echo $pagCss ; ?>>
    <tr>
        <td style="width: 30% ;"><img src="<?php echo $this->basePath(),'/images/VilaVelhaLogotipoM.png'; ?>" /></td>
        <td valing="middle">
            <h2>RELATÓRIO DE FATURA</h2>
            <p style="text-align:right;"><? echo date('d/m/Y h:i') , 'Hs'; ?></p>
            <table style="width: 100% ;" >
                <tr>
                    <td></td>
                    <td><? echo $ent->getAdministradora()->getId(), ' - ', $ent->getAdministradora(); ?></td>
                </tr>
            </table>
        </td>
    </tr>
</table>
    <?    
    endif;
    // Verifica a sequencia da parcela e a forma de pagamento
    $fPg = $ent->getFormaPagto();
    $comissao = $ent->getComissao();
    $ocupacao = $ent->getOcupacao();
    $frmPagto = isset($this->formaPagto[$fPg]) ? $this->formaPagto[$fPg] : 'Ñ encontrado' . $fPg;
    if($ent->getValidade() == 'mensal'){
        $frmPagto = 'Pag Mensal';
    }  
    switch ($fPg) {
        case '01':
            $parcela = 'A Vista';
            $parc    = '1/1';
            if($ent->getValidade() == 'mensal'){
                $parcela = 'Pag Mensal';
            } 
            break;
        case '02':
            $prc = $mesSel - $ent->getInicio('obj')->format('m') + 1;
            $parcela = $parc = $prc . '/2';
            break;
        case '03':
            $prc = $mesSel - $ent->getInicio('obj')->format('m') + 1;
            $parcela = $parc = $prc . '/3';
            break;
        case '04':
            $prc = $mesSel - $ent->getInicio('obj')->format('m') + 1;
            $parcela = $parc = $prc . '/4';
            break;
        default:
            break;
    } 
    if($parcelaOld != $parcela OR $ocupacaoOld != $ocupacao OR $comissaoOld != $comissao):
        if(!empty($parcelaOld)):
?>
        <tr>
                <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
                <td class="Bl Bb Bt" align="center">Total</td>
                <td class="Bl Bb Bt" align="center" colspan="3"><? echo $qtd ?></td>
                <td class="Bl Bb Bt Br" align="right" colspan="2"><? echo number_format($total, 2, ',', '.') ?></td>
        </tr> 
        </table> 
        <br />
        <table class="Bt Bb"  style="width: 100% ;">
        <tr><th class="Bl Br" align="center">Observação: </th></tr>  
        <tr>  
                <td class="Bl Bb Bt Br F1">Caso a somatória dos prêmios de cada forma de pagamento for inferior a R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão
        de apólice.</td>
        </tr>  
        </table> 
        <br />
        <?
            $qtd = 0;
            $total = 0;
        ?>
        <? endif; ?>
        <? 
        $parcelaOld  = $parcela;
        $ocupacaoOld = $ocupacao;
        $comissaoOld = $comissao;
        ?>

    <table class="Bt Bb"  class="data" style="width: 100% ;">
    <tr class="F2">
        <th class="Bl F2">Comissão: <? echo $this->comissaoAp[number_format($comissao, 2, ',', '.')]; ?></th>
            <th class="Bl">Tipo: <? switch ($ocupacao){
                                case '01': echo 'Comércio ';break; 
                                case '02': echo 'Residencial'; break; 
                                case '03': echo 'Industria'; break; 
                                default  : echo 'Desconhecido';}
                                 ?></th>
            <th class="Bl">Forma Pagto.: <? echo $frmPagto; ?></th>
            <th class="Br">Parcela: <? echo $parcela; ?></th>
    </tr>  
    </table>    
    <table class="Bt Bb" style="width: 100% ;">
    <tr class="F1">
            <th class="Bl" style="width:9%;">Ref. do Imóvel</th>
            <th class="Bl" style="width:15%;">Locador</th>
            <th class="Bl" style="width:15%;">Locatário</th>
            <th class="Bl" style="width:25%;">Local do Risco</th>
            <th class="Bl" style="width:15%;">Ocupação</th>
            <th class="Bl" style="width:8%;">Valor<br>Aluguel</th>
            <th class="Bl" style="width:7%;">Vigência<br>Inicial</th>
            <th class="Bl Br">Valor Parc.</th>
    </tr>    

    <? endif; ?>
    <?
    $valor = $ent->getPremioTotal() / intval($ent->getFormaPagto());
    $total += $valor;
    $qtd++;
    $total2 += $valor;
    $qtd2++;
    $adm = $admAtual;
    ?>
<tr class="F1">
	<td class="Bl Bb Bt"><? echo $ent->getRefImovel() ?></td>
	<td class="Bl Bb Bt F8"><? echo $ent->getLocadorNome() ?></td>
	<td class="Bl Bb Bt F8"><? echo $ent->getLocatarioNome() ?></td>
	<td class="Bl Bb Bt F8"><? echo $ent->getImovel() ?></td>
	<td class="Bl Bb Bt F8"><? echo $ent->getAtividade()->getDescricao() ?></td>
        <td class="Bl Bb Bt" align="right"><? echo number_format($ent->getValorAluguel(), 2, ',', '.') ?></td>
	<td class="Bl Bb Bt" align="right"><? echo $ent->getInicio() ?></td>
	<td class="Bl Bb Bt Br" align="right"><? echo number_format($valor, 2, ',', '.') ?></td>
</tr> 
<? endforeach; ?>
<? if($qtd != 0): ?>

<tr>
        <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
        <td class="Bl Bb Bt" align="center">Total</td>
        <td class="Bl Bb Bt" align="center" colspan="3"><? echo $qtd ?></td>
        <td class="Bl Bb Bt Br" align="right" colspan="2"><? echo number_format($total, 2, ',', '.') ?></td>
</tr> 
</table> 
<br />
<table class="Bt Bb"  style="width: 100% ;">
<tr><th class="Bl Br" align="center">Observação: </th></tr>  
<tr>  
        <td class="Bl Bb Bt Br F1" rowspan="3">Caso a somatória dos prêmios de cada forma de pagamento for inferior a R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão
de apólice.</td>
</tr>  
<? endif; ?>
</table> 
<br />
<table class="Bt Bb"  style="width: 100% ;">
<tr>
        <td class="Bl Bb Bt" align="center">Total Geral</td>
        <td class="Bl Bb Bt" align="center">Seguros</td>
        <td class="Bl Bb Bt" align="right"><? echo $qtd2 ?></td>
        <td class="Bl Bb Bt" align="center">Valor</td>
        <td class="Bl Bb Bt Br" align="right"><? echo number_format($total2, 2, ',', '.') ?></td>
</tr> 
</table> 
<br />

<div align='center' class="noPrint">
<table width="100%">
    <tr>
        <td align='center' width="50%">
            <input type="submit" name="fecharSel" id="fecharSel" class="btn-success" value="Imprimir" onclick="return imprimi()">
        </td>
        <td align='center'>
            <input type="button" name="enviar" id="enviar" class="btn-success" value="Gerar Excel" onclick="toExcel('')">            
        </td>
    </tr>
</table>
</div>
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
    <input type="hidden" name="mesFiltro" value="<?=$mesSel ?>">
</form>
<script language="javascript">
    function gerarMapa(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'gerarMapa')); ?>";
        envia(tar,'gerar');        
    }
    function imprimi(){
        window.print();
        return false;
    }
    function toExcel(){
        var tar2 = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'toExcelRelatorio')); ?>";
        envia(tar2, "");
        return false;
    } 
</script>
