<?php
//Montar tabela para exibição xls.
$tabela_dados = "" ;

if(empty($this->data)){
    echo '<tr><td>Nenhum resultado foi encontrado!!!!</td></tr></table>';
    exit();    
}
$cor = "";
$total    = 0;
$qtd      = 0;
$total2   = 0;
$qtd2     = 0;
$adm      = 0;
$tipo     = '';
$comissaoOld = '';
$comissao = '';
$ocupacaoOld = '';
$ocupacao = '';
$parcelaOld = '';
$parcela  = '';
$parc     = '';
$mesSel   = $this->date['mesFiltro'];
foreach($this->data as $ent): 
    // Verifica se trocou de adm e verifica se tem necessidade de finalizar tabela da adm anterior
    $admAtual = $ent->getAdministradora()->getId();
    if($adm != $admAtual):
        if($adm != 0):
            $total_form = number_format($total, 2, ',', '.');
            $tabela_dados .= <<<EOT
                <tr>
                        <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
                        <td class="Bl Bb Bt" align="center">Total</td>
                        <td class="Bl Bb Bt" align="center" colspan="3">{$qtd}</td>
                        <td class="Bl Bb Bt Br" align="right" colspan="2">{$total_form}</td>
                </tr> 
                </table> 
                <br />
                <table class="Bt Bb"  style="width: 100% ;">
                <tr><th class="Bl Br" align="center">Observação: </th></tr>  
                <tr>  
                        <td class="Bl Bb Bt Br F1" colspan="8">Caso a somatória dos prêmios de cada forma de pagamento for inferior a R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão
                de apólice.</td>
                </tr>  
                </table> 
                <br />
EOT;
            $qtd = 0;
            $total = 0;          
            $pagCss = ' class="quebra"';
            $parcelaOld = '';
        else:
            $pagCss = '';            
        endif; 
        $date = date('d/m/Y h:i');
        $tabela_dados .= <<<EOT
        <table style="width: 100% ;" {$pagCss}>
            <tr>
                <td valign="middle" align="center" colspan="8">
                    <h2>RELATÓRIO DE FATURA</h2>
                    <p style="text-align:right;">{$date} Hs</p>
                    <h1>{$ent->getAdministradora()->getId()} - {$ent->getAdministradora()}</h1>
                </td>
            </tr>
        </table>
EOT;
    endif;
    // Verifica a sequencia da parcela e a forma de pagamento
    $fPg = $ent->getFormaPagto();
    $comissao = $ent->getComissao();
    $ocupacao = $ent->getOcupacao();
    $frmPagto = isset($this->formaPagto[$fPg]) ? $this->formaPagto[$fPg] : 'Ñ encontrado' . $fPg;
    if($ent->getValidade() == 'mensal'){
        $frmPagto = 'Pag Mensal';
    }  
    switch ($fPg) {
        case '01':
            $parcela = 'A Vista';
            $parc    = '1/1';
            if($ent->getValidade() == 'mensal'){
                $parcela = 'Pag Mensal';
            } 
            break;
        case '02':
            $prc = $mesSel - $ent->getInicio('obj')->format('m') + 1;
            $parcela = $parc = $prc . '/2';
            break;
        case '03':
            $prc = $mesSel - $ent->getInicio('obj')->format('m') + 1;
            $parcela = $parc = $prc . '/3';
            break;
        default:
            break;
    } 
    if($parcelaOld != $parcela OR $ocupacaoOld != $ocupacao OR $comissaoOld != $comissao):
        if(!empty($parcelaOld)):
            $total_form = number_format($total, 2, ',', '.');
            $tabela_dados .= <<<EOT
        <tr>
                <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
                <td class="Bl Bb Bt" align="center">Total</td>
                <td class="Bl Bb Bt" align="center" colspan="3">{$qtd}</td>
                <td class="Bl Bb Bt Br" align="right">{$total_form}</td>
        </tr> 
        </table> 
        <br />
        <table class="Bt Bb"  style="width: 100% ;">
        <tr><th class="Bl Br" align="center">Observação: </th></tr>  
        <tr>  
                <td class="Bl Bb Bt Br F1" colspan="8">Caso a somatória dos prêmios de cada forma de pagamento for inferior a 
                   R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão de apólice.</td>
        </tr>  
        </table> 
        <br />
EOT;
            $qtd = 0;
            $total = 0;
        endif;
        $parcelaOld  = $parcela;
        $ocupacaoOld = $ocupacao;
        $comissaoOld = $comissao;
        $tabela_dados .= <<<EOT
    <table class="Bt Bb"  class="data" style="width: 100% ;">
    <tr class="F2">
        <th class="Bl F2">Comissão: {$this->comissaoAp[number_format($comissao, 2, ',', '.')]}</th>
            <th class="Bl">Tipo: 
EOT;
                switch ($ocupacao){
                    case '01': $tabela_dados .= 'Comércio '    ; break; 
                    case '02': $tabela_dados .= 'Residencial'  ; break; 
                    case '03': $tabela_dados .= 'Industria'    ; break; 
                    default  : $tabela_dados .= 'Desconhecido' ;
                }
        $tabela_dados .= <<<EOT
            </th>
            <th class="Bl">Forma Pagto.: {$frmPagto}</th>
            <th class="Br">Parcela: {$parcela}</th>
    </tr>  
    </table>    
    <table class="Bt Bb" style="width: 100% ;">
    <tr class="F1">
            <th class="Bl" style="width:9%;">Ref. do Imóvel</th>
            <th class="Bl" style="width:15%;">Locador</th>
            <th class="Bl" style="width:15%;">Locatário</th>
            <th class="Bl" style="width:25%;">Local do Risco</th>
            <th class="Bl" style="width:15%;">Ocupação</th>
            <th class="Bl" style="width:8%;">Valor<br>Aluguel</th>
            <th class="Bl" style="width:7%;">Vigência<br>Inicial</th>
            <th class="Bl Br">Valor Parc.</th>
    </tr>    

EOT;
    endif;
    $valor = $ent->getPremioTotal() / intval($ent->getFormaPagto());
    $total += $valor;
    $qtd++;
    $total2 += $valor;
    $qtd2++;
    $adm = $admAtual;
    $valor_format = number_format($ent->getValorAluguel(), 2, ',', '.');
    $valor2_format = number_format($valor, 2, ',', '.');
    $tabela_dados .= <<<EOT
<tr class="F1">
	<td class="Bl Bb Bt">{$ent->getRefImovel()}</td>
	<td class="Bl Bb Bt F8">{$ent->getLocadorNome()}</td>
	<td class="Bl Bb Bt F8">{$ent->getLocatarioNome()}</td>
	<td class="Bl Bb Bt F8">{$ent->getImovel()}</td>
	<td class="Bl Bb Bt F8">{$ent->getAtividade()->getDescricao()}</td>
        <td class="Bl Bb Bt" align="right">{$valor_format}</td>
	<td class="Bl Bb Bt" align="right">{$ent->getInicio()}</td>
	<td class="Bl Bb Bt Br" align="right">{$valor2_format}</td>
</tr> 
EOT;
endforeach; 


if($qtd != 0): 
    $total_form = number_format($total, 2, ',', '.');
    $tabela_dados .= <<<EOT
    <tr>
            <td class="Bl Bb Bt" colspan="3">&nbsp;</td>
            <td class="Bl Bb Bt" align="center">Total</td>
            <td class="Bl Bb Bt" align="center" colspan="3">{$qtd}</td>
            <td class="Bl Bb Bt Br" align="right">{$total_form}</td>
    </tr> 
    </table> 
    <br />
    <table class="Bt Bb"  style="width: 100% ;">
    <tr><th class="Bl Br" align="center">Observação: </th></tr>  
    <tr>  
            <td class="Bl Bb Bt Br F1" colspan="8">Caso a somatória dos prêmios de cada forma de pagamento for inferior a 
                R$ 107,38 será considerado o prêmio de R$ 107,38 por emissão de apólice.</td>
    </tr>  
EOT;
endif;

$total2_form = number_format($total2, 2, ',', '.');
$tabela_dados .= <<<EOT
</table> 
<br />
<table class="Bt Bb"  style="width: 100% ;">
<tr>
        <td class="Bl Bb Bt" align="center">Total Geral</td>
        <td class="Bl Bb Bt" align="center">Seguros</td>
        <td class="Bl Bb Bt" align="right">{$qtd2}</td>
        <td class="Bl Bb Bt" align="center">Valor</td>
        <td class="Bl Bb Bt Br" align="right">{$total2_form}</td>
</tr> 
</table> 
EOT;


//Nome do arquivo
$filename = "Relatorio_Fatura_" . date('d-m-Y_H-i-s');
//XLS - exibe a tabela pronta em html para XLS
header("Content-Type:  application/vnd.ms-excel; charset=UTF-8; encoding=UTF-8");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header ("Content-Disposition: attachment; filename=\"".$filename.".xls\"" );
print(($tabela_dados));
