<h3>Login</h3>

<br />

<?php if ($this->error): ?>
    <p><b>Usuário ou senha inválidos</b></p>
<?php endif; ?>


<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin-auth'));

$form->prepare();

echo 
$this->FormDefault(['legend' => 'Digite seu Login e Senha'],'inicio',$this, $form),
    "<td>",
        $this->FormDefault(['subOpcao' => 'hidden']),
        $this->FormDefault(['email' => 'textLine']),
        $this->FormDefault(['password' => 'passLine']),
    "</td>\r",
$this->FormDefault(['submit' => 'submit'],'fim');

?>

<script language="javascript">
    var formName = '<?php echo $form->getName(); ?>';
    function pressEnterOrTab(obj, e){
        n = obj.name;
        switch(n){
            case 'password':
                entra();
                break;
        }
    }
    function entra(){
        envia('/admin/auth','',formName);
    }
</script>