<div style="width: 90%; margin: 0 5%">
<table style="border: solid 1px #000000; width: 100%; background-color: #EDEEEF">
    <tr>
        <td style="padding: 0 5% ; width: 35%;"><img src="images/logo_vila_velha_seguros.png" />
            <h2>Residência</h2>
            <p>Proteger o seu patrimônio contra eventos externos é garantir também a proteção da sua família.
No Seguro Residencial, você encontra as melhores condições de indenização e Assistência 24h sem sair de casa. </p>
         </td>
        <td><img src="images/residencia_seguro_mao.jpg" /></td>
    </tr>    
</table>
<br />

<table style="border: solid 1px #000000; width: 100%;">
    <tr>
        <td>
            <ul class="nav-list">
                <li>Menu</li>
                <li>Noticias</li>
                <li>Contato</li>
                <li>Serviços</li>
                <li><a href="https://srvlinux.tcmed.com.br/downloads/TeamViewer_Setup_pt.exe">Suporte Instalador.</a></li>
                <li><a href="https://srvlinux.tcmed.com.br/downloads/tvqs.exe">Suporte sem instalação.</a></li>
            </ul>
        </td>
        <td style="padding: 0 5% ; width: 80%; background-color: #EDEEEF">
            <h1 style="text-align: center">Notícias</h1><br />
            <h3>Você sabia que o seguro residencial ajuda a garantir a segurança da sua casa durante as férias?</h3><br />
            <p>Com o início da temporada das férias, muitas famílias se preparam para viajar e fugir da rotina. A ansiedade toma conta do ambiente e muitas pessoas esquecem de que é preciso se prevenir ao deixar a casa desocupada.</p>
            <p>Muitas pessoas se preocupam apenas com a manutenção do carro antes de viajar, mas esquecem de que a casa fica desprotegida na ausência dos proprietários e torna-se alvo fácil de ladrões.  </p>
            <p>Antes de viajar, algumas pessoas tomam a precaução de reforçar a proteção do imóvel com trancas e cadeados, mas além de furtos, também é necessário se preocupar com possíveis incêndios, danos elétricos e outras. O Seguro Residência é o melhor meio para garantir o ressarcimento em decorrência de sinistros e o seu custo é baixo em relação à proteção financeira que se recebe em troca. </p>
            <p>O Seguro Residência oferece assistência 24h com diversos serviços como: chaveiro, eletricista, reparos hidráulicos, substituição de telhas, entre outros. No entanto, é preciso ficar atento quanto à cobertura na hora de contratar o seguro, pois ela varia de acordo com a seguradora e o plano. </p>
            <p>Antes de viajar entre em contato com a Vila Velha e não saia sem antes contratar um seguro para sua residência.</p>
            <p></p>
        </td>
    </tr>    
</table>

<br />
<p>
    Av. Ipiranga, 313 | República 01046-010 | São Paulo | SP faleconosco@vilavelha.com.br | Tel (11) 3226-9600
</p>
</div>
