<h1>Seguros Fechados</h1>
<br />

<?php
$coluns = array(
    'ID',
    'Seguradora',
    'Atividade',
    'Classe',
    'Inicio',
    'Fim',
    'Locador',
    'Locatario',
    'Valor',
    'Status',
    'Imprimir'
    );
$td = [
    'class="r"',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'class="r"',
    '',
];
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));

$lambda = function($value){
        echo "\t<td>",
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>',
             "</td>\n";   
    };
    
$this->ViewIndex('setFuncEdit',$lambda);    
    
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId() . '/' . $entity->getCodAno(),
        $entity->getSeguradora(),
        $entity->getAtividade(),
        $entity->getTaxa()->getClasse(),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->floatToStr('premioTotal'),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>