<h3>Resultado Período Antes 
<? echo $this->date['inicio']->format('d/m/Y'); ?> até <? echo $this->date['fim']->format('d/m/Y'); 
$this->date['inicio']->add(new \DateInterval('P1Y'));
$this->date['fim']->add(new \DateInterval('P1Y'));
?><br />
Resultado Período Atual <? echo $this->date['inicio']->format('d/m/Y'); ?> até <? echo $this->date['fim']->format('d/m/Y'); ?>
</h3>
<?php
$coluns = array(
    'Seq',
    'U.E.',
    'Administradora',
    'Anterior<br />Quant.<br />Seguros',
    'Anterior<br />Prêmio ',
    'Quant.<br />Seguros',
    'Prêmio'
    );
$td     = array(
    'class="r"',
    'class="r"',
    '',
    'class="r"',
    'class="r"',
    'class="r"',
    'class="r"',
);
echo $this->ViewIndex('table', 'data'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td, 'tr' => 'class="f7"','editLine' => false));

$totFechado = $totFechadoA = $seq =  $totPremio =  $totPremioA =  0;
foreach($this->data as $key => $values){
    // Mudou adm exibe resulta e reseta valores
    $seq ++;
    echo $this->ViewIndex('line',array('data' =>[  $seq, 
                                                    $values['id'], 
                                                    $values['nome'], 
                                                    $values['antes']['qtd'], 
                                                    number_format($values['antes']['total'], 2, ',', '.'),
                                                    $values['atual']['qtd'], 
                                                    number_format($values['atual']['total'], 2, ',', '.')
                                                ],
                                        'tr' => 'class="f6"'));
    // SOMATORIA GERAL 
    $totFechadoA += $values['antes']['qtd'];
    $totPremioA  += $values['antes']['total'];
    $totFechado += $values['atual']['qtd'];
    $totPremio  += $values['atual']['total'];
}
// Totaliza Dados
echo $this->ViewIndex('tfoot',array('data' => ['', '', 'Totais', $totFechadoA, number_format($totPremioA, 2, ',', '.'), $totFechado, number_format($totPremio, 2, ',', '.')], 'tr' => 'class="f7"'));

echo $this->ViewIndex('close');

?>
<div class="noPrint" align="center">
<br />
<table width="100%">
    <tr>
        <td align='center'>
            <input type="button" name="voltar" id="voltar" class="btn-success" value="Tela Anterior" onclick="window.history.back()">            
        </td>
    </tr>
</table>
</div>
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function printProp(adm){
        var tar2 = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'printProposta')); ?>";
        envia(tar2, adm);
        return false;
    }  
    function sendEmail(adm){
        var tar2 = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'sendEmail')); ?>";
        envia(tar2, adm, null,'email');
    }    
</script>
