<h1>Seguros Fechados</h1>
<br />
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<?php

    $form = $this->form; 
    $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
    $form->prepare();
    echo 
    $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
        "<td>\r",
            $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp','user'], 'hidden'),
            $this->FormDefault([
                'name' => 'usuarioNome',
                'icone' => 'icon-search',
                'js' => 'autoCompUsuario()',
                'span' => "popUser' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['id'], 'text'),
        "</td><td>\r",
            $this->FormDefault(['dataI'], 'calend'),
        "</td><td>\r",
            $this->FormDefault(['dataF'], 'calend'),
        "</td><td>\r",
        "</td><td style='vertical-align: middle;' rowspan='2'>\r",
            $this->FormDefault(['enviar'], 'submitOnly'),
        "</td>\r",
    "</tr><tr>\r",
        "<td>\r",
            $this->FormDefault(['administradora'=>'hidden']),
            $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['status'=>'radio']),
        "</td><td>\r",
        "</td><td>\r",
        "</td>\r",

    $this->FormDefault([],'fim');
    
$coluns = array(
    'ID',
    'Administradora',
    'Seguradora',
    'Atividade',
    'Classe',
    'Inicio',
    'Fim',
    'Locador',
    'Locatario',
    'Valor',
    'Status',
    'Imprimir'
    );
$td = [
    'class="r"',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'class="r"',
    '',
];
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));

$lambda = function($value){
        echo "\t<td>",
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>',
             "</td>\n";   
    };
    
$this->ViewIndex('setFuncEdit',$lambda);    
    
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId() . '/' . $entity->getCodAno(),
        $entity->getAdministradora(),
        $entity->getSeguradora(),
        $entity->getAtividade(),
        $entity->getTaxa()->getClasse(),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->floatToStr('premioTotal'),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    } 
    function autoCompUsuario(){
        document.getElementById('autoComp').value = 'usuarioNome';
        var filtros = 'autoComp,usuarioNome';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'users','action'=>'autoComp')); ?>";
        var returns = Array('user','usuarioNome');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popUser',returns,'2',functionCall);
    }
    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }  
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>