<h2>Resultado Período Antes <? echo $this->date['inicio']->format('d/m/Y'); ?> até <? echo $this->date['fim']->format('d/m/Y'); 
$this->date['inicio']->add(new \DateInterval('P1Y'));
$this->date['fim']->add(new \DateInterval('P1Y'));
?></h2>
<h2>Resultado Período Atual <? echo $this->date['inicio']->format('d/m/Y'); ?> até <? echo $this->date['fim']->format('d/m/Y'); ?></h2>
<br />
<?php
$coluns = array(
    'Seq',
    'U.E.',
    'Administradora',
    'Anterior Quant. Seguros',
    'Anterior Prêmio ',
    'Quant. Seguros',
    'Prêmio'
    );
$td     = array(
    'class="r"',
    'class="r"',
    '',
    'class="r"',
    'class="r"',
    'class="r"',
    'class="r"',
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => false));

$totFechado = $totFechadoA = $seq =  $totPremio =  $totPremioA =  0;
foreach($this->data as $key => $values){
    // Mudou adm exibe resulta e reseta valores
    $seq ++;
    echo $this->ViewIndex('line',array('data' =>[  $seq, 
                                                    $values['id'], 
                                                    $values['nome'], 
                                                    $values['antes']['qtd'], 
                                                    number_format($values['antes']['total'], 2, ',', '.'),
                                                    $values['atual']['qtd'], 
                                                    number_format($values['atual']['total'], 2, ',', '.')
                                                ]));
    // SOMATORIA GERAL 
    $totFechadoA += $values['antes']['qtd'];
    $totPremioA  += $values['antes']['total'];
    $totFechado += $values['atual']['qtd'];
    $totPremio  += $values['atual']['total'];
}
// Totaliza Dados
echo $this->ViewIndex('tfoot',array('data' => ['', '', 'Totais', $totFechadoA, number_format($totPremioA, 2, ',', '.'), $totFechado, number_format($totPremio, 2, ',', '.')]));

echo $this->ViewIndex('close');

?>
<br />
<table width="100%">
    <tr>
        <td align='center'>
            <input type="button" name="voltar" id="voltar" class="btn-success" value="Tela Anterior" onclick="window.history.back()">            
        </td>
    </tr>
</table>
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function printProp(adm){
        var tar2 = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'printProposta')); ?>";
        envia(tar2, adm);
        return false;
    }  
    function sendEmail(adm){
        var tar2 = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'sendEmail')); ?>";
        envia(tar2, adm, null,'email');
    }    
</script>
