<?php 
if($this->resultSet){
    echo "ok|s|",
         'X|c|',
         'X|c|',
         'ID|c|',
         'Nome|c|',
         '|s|';
    $cont = 0;
    foreach($this->resultSet as $entity){
        if($entity->getId() == 1)continue; //pula o id 1 ele é uma referencia vazia
        if($cont > 0)echo "|s|";
        $cont++;
        echo $entity->getId(), "|c|"; 
        echo $entity->getNome(), "|c|"; 
        echo $entity->getId(), "|c|"; 
        echo $entity->getNome(), "|c|"; 
    }
}else
    echo "vazio|s|";