<h3>Alterar Senha do usuário</h3>

<br />
<p><span class="add-on hand" onClick="voltar();"><i class="icon-backward"></i>Voltar</span></p>
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin-interna',array('controller'=>'users','action'=>'alteraSenha')));

$form->prepare();
echo 
$this->FormDefault(['legend' => 'Faça sua alteração:', 'hidden' => 'id'],'inicio',$this, $form),
    "<td>\r",
        $this->FormDefault(['ajaxStatus','autoComp','subOpcao','administradora'],'hidden'),
        $this->FormDefault(['email'],'hidden'),
        $this->FormDefault(['password3' => 'passLine']),
        $this->FormDefault(['password'  => 'passLine']),
        $this->FormDefault(['password2' => 'passLine']),
    "</td>\r",
$this->FormDefault([],'fieldFim');

$this->FormDefault(['submit' => 'enviar','noField' => true],'fim');

?>
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    
    var tar = '<?php echo $this->url($this->matchedRouteName,$this->params); ?>';
    var formName = '<?php echo $this->formName ?>';
    function salvar(){
        if(document.getElementById('password').value != document.getElementById('password2').value){
            alert("Senha digita não é igual a anterior!");
            return false;
        }
        envia(tar,'salvar',formName);
        return false;
    }
    function voltar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'index','action'=>'bemVindo')); ?>";
        envia(tar,'',formName);
    }
</script>