<p>
<?
$hr = date(" H "); 
echo ($hr <= 12)?'Bom dia!':'Boa tarde!'; ;
?> 
</p>
<br />
<br />
<p>
Segue relação de seguros não fechados, para seu conhecimento e providencias.
</p>
<br />
<br />
<table style="border-top: solid #000 1px; border-left: solid #000 1px;"  cellspacing="0" cellpadding="0">
    <thead>
        <tr style="background-color: #d9d9d9;">
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Imóvel</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Vigência</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Locador</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Locatário</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Endereço</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Status</th>
        </tr>
    </thead>
    <tbody>
<? foreach ($this->data as $value) : ?>
        <tr>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[0]; ?></p></td>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[1]; ?></p></td>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[2]; ?></p></td>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[3]; ?></p></td>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[4]; ?></p></td>
            <td style="border-bottom:solid #000 1px;border-right:solid #000 1px;font-size:8pt;"><p><? echo $value[5]; ?></p></td>
        </tr>
<? endforeach; ?>        
    </tbody>        
</table>
<br />
<p>
    Atenciosamente,
    <br />
    <br />
    <b>Vila Velha Corretora de Seguros</b>
    <br />
    (11) 3226-9708
</p>