<p>
Bom dia! 
</p>
<br />
<br />
    <? echo $this->nome;?>,
<br />
<br />
<p>
    Os seguros contratados para os imóveis abaixo estão enquadrados com <strong>Edifício Desocupado</strong>, caso os 
    mesmos já tenham sido alugados favor nos informar o novo ramo de atividade para atualização do certificado de seguro.
</p>
<p>
    Informamos ainda que, se o seguro for contratado como edifício desocupado e no momento de um eventual sinistro o 
    imóvel estiver ocupado, <span style="color: #FF0000;">o segurado poderá ser prejudicado em uma eventual indenização.</span>
</p>
<br />
<br />
<table style="border-top: solid #000 1px; border-left: solid #000 1px;"  cellspacing="0" cellpadding="0">
    <thead>
        <tr style="background-color: #d9d9d9;">
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Início Vigência</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Fim Vigência</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Locatário</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Locador</th>
            <th style="border-bottom: solid #000 1px; border-right:  solid #000 1px;">Endereço</th>
        </tr>
    </thead>
    <tbody>
<? foreach ($this->data as $value) : ?>
        <tr>
            <td style="border-bottom: solid #000 1px; border-right:  solid #000 1px;"><? echo $value[0]; ?></td>
            <td style="border-bottom: solid #000 1px; border-right:  solid #000 1px;"><? echo $value[1]; ?></td>
            <td style="border-bottom: solid #000 1px; border-right:  solid #000 1px;"><? echo $value[2]; ?></td>
            <td style="border-bottom: solid #000 1px; border-right:  solid #000 1px;"><? echo $value[3]; ?></td>
            <td style="border-bottom: solid #000 1px; border-right:  solid #000 1px;"><? echo $value[4]; ?></td>
        </tr>
<? endforeach; ?>        
    </tbody>        
</table>
<br />
<br />
<p>
    Atenciosamente,
    <br />
    <br />
    <b>Vila Velha Corretora de Seguros</b>
    <br />
    Departamento Incêndio Locação
    <br />
    (11) 3226-9708
</p>