<p>
<?
$hr = date(" H "); 
echo ($hr <= 12)?'Bom dia!':'Boa tarde!'; ;
?> 
</p>
<p>
    Email de aviso de Limite para Vistoria de seguro.
</p> 
<p>
    Abaixo segue dados do seguro.
</p> 
<p>
    Seguro numero: <? echo $this->data['seguro']; ?>.
</p>  
<p>
    Administradora: <? echo $this->data['nome']; ?>.
</p>  
<p>
    imovel: <? echo $this->data['imovel']; ?>.
</p>  
<p>
    locador: <? echo $this->data['locador']; ?>.
</p>  
<p>
    locatario: <? echo $this->data['locatario']; ?>.
</p>  
<p>
    Atenciosamente,
    <br />
    <br />
    <b>Vila Velha Corretora de Seguros</b>
    <br />
    Departamento Incêndio Locação
    <br />
    (11) 3226-9708
</p>