<p>
    Cancelamento imovel Abaixo efetuado com sucesso.
</p> 
<p>
    Abaixo segue dados do seguro cancelado.
</p> 
<p>
    Seguro numero: <? echo $this->data['seguro']; ?>.
</p>  
<p>
    Local do Risco: <? echo $this->data['imovel']; ?>.
</p>  
<p>
    Locador: <? echo $this->data['locador']; ?>.
</p>  
<p>
    Locatario: <? echo $this->data['locatario']; ?>.
</p>  
<p>
    Motivo: <? echo $this->data['motivo']; ?>.
</p>  
<p>
    Atenciosamente,
    <br />
    <br />
    <b>Vila Velha Corretora de Seguros</b>
    <br />
    Departamento Incêndio Locação
    <br />
    (11) 3226-9708
</p>