<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vila Velha Seguros')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->        
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php 
        echo $this->headScript()
                  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                  ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js')
                  ->prependFile($this->basePath() . '/js/ajax.js')
                  ->prependFile($this->basePath() . '/js/ajaxCep.js')
                  ->prependFile($this->basePath() . '/js/ajaxAutoComp.js')
                  ->prependFile($this->basePath() . '/js/funcoes.js')
        ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('livraria-home') ?>">Seguros Admin</a>
                    <div class="nav-collapse">
                    <?php if ($user = $this->UserIdentity('LivrariaAdmin')){
                              if($user->getTipo() == 'admin')
                                  echo $this->navigation('NavAdmin')->menu()->setUlClass('nav'); 
                              else
                                  echo $this->navigation('NavUser')->menu()->setUlClass('nav'); 
                          }else
                              echo $this->navigation('Navigation')->menu()->setUlClass('nav');
                    ?>    
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>PC Watakabe Sistemas</p>
                <? if($user) echo '<p>', $user->getNome(),' ', $user->getEmail(),' ', $user->getTipo(), '</p>' ;  ?>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
