<?php echo $this->doctype(); ?>
<html>
    <head>
        <!-- Mimic Internet Explorer 7 -->
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" >
        <meta http-equiv="content-language" content="pt-br" />
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <?php echo $this->headTitle('Vila Velha Seguros')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->        
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/dhtmlgoodies_calendar.css')
                ->prependStylesheet($this->basePath() . '/css/print.css','print')
        ?>

        <!-- Scripts -->
        <?php 
        echo $this->headScript()
                  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                  ->prependFile('/js/jquery.min.js')
                  ->prependFile($this->basePath() . '/js/ajax.js')
                  ->prependFile($this->basePath() . '/js/ajaxCep.js')
                  ->prependFile($this->basePath() . '/js/ajaxAutoComp.js')
                  ->offsetSetFile(96, $this->basePath() . '/js/jquery.validate.js')
                  ->offsetSetFile(97, $this->basePath() . '/js/util.validate.js')
                  ->offsetSetFile(98, $this->basePath() . '/js/bootstrap.min.js')
                  ->offsetSetFile(99, $this->basePath() . '/js/jquery.maskMoney.js')
                  ->offsetSetFile(100, $this->basePath() . '/js/funcoes.js')
                  ->prependFile($this->basePath() . '/js/dhtmlgoodies_calendar.js') , "\n";
        ?>
<style type="text/css" media="print">
    .quebra    { 
        page-break-before: always ;
    }
    .noPrint {
        display: none;
    }
</style>
    </head>
    <body>
        <div class="navbar navbar-fixed-top noPrint">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Incêndio Locação</a>
                    <div class="nav-collapse">
                    <?php   if ($user = $this->UserIdentity('LivrariaAdmin')){
                                switch ($user->getMenu()) {
                                case 'adm':
                                    echo $this->navigation('NavAdmin')->menu()->setUlClass('nav'); 
                                    break;
                                case 'adm2':
                                    echo $this->navigation('NavNoAdmin')->menu()->setUlClass('nav'); 
                                    break;
                                case 'imob':
                                    echo $this->navigation('NavUser')->menu()->setUlClass('nav'); 
                                    break;
                                default:
                                    echo $this->navigation('Navigation')->menu()->setUlClass('nav'); 
                                    break;
                                }
                            }else{
                                echo $this->navigation('Navigation')->menu()->setUlClass('nav');                              
                            }
                    ?>    
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
            <div id="footerLayout" class="noPrint">
                <hr>
                <footer>
                    <? if($user) echo '<p>', $user->getNome(),' ', $user->getEmail(),' ', $user->getTipo(), '</p>' ;  ?>
                    <!--<p>PC Watakabe Sistemas</p>-->
                </footer>
            </div>
        </div> <!-- /container -->
        <form name="fmenu" id="fmenu" method="POST">
            <input name="scrolX" type="hidden" />
            <input name="scrolY" type="hidden" />
        </form>
<?php //echo $this->inlineScript() ?>
    </body>
</html>
