<h1>Comissaos e Multiplos</h1>
<br />
<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Comissao e Multiplos</span></p>
<?php
$form = $this->form; 

$form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));

$form->prepare();
echo 
$this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
    "<td>\r",
        $this->FormDefault(['administradora', 'ajaxStatus', 'subOpcao'], 'hidden'),
        $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'iconeLine'),
    "</td>\r",
$this->FormDefault([],'fim');

$coluns = array(
    'ID'
    , 'Administradora'
    , 'Comercial %'
    , 'Residencial %'
    , 'Comerc. Mult. Incêncio'
    , 'Comerc. Mult. Conteúdo'
    , 'Comerc. Mult. Aluguel'
    , 'Comerc. Mult. Eletrico'
    , 'Comerc. Mult. Vendaval'
    , 'Reside. Mult. Incêncio'
    , 'Reside. Mult. Conteúdo'
    , 'Reside. Mult. Aluguel'
    , 'Reside. Mult. Eletrico'
    , 'Reside. Mult. Vendaval'
    , 'Inicio'
    , 'Fim'
    , 'Status'
    , 'Ação'
);
$td = array(
    ''
    , ''
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , 'class="r"'
    , ''
    , ''
    , ''
    , ''
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getAdministradora(),
        $entity->floatToStr('Comissao'),
        $entity->floatToStr('comissaoRes'),
        $entity->floatToStr('multIncendio'),
        $entity->floatToStr('multConteudo'),
        $entity->floatToStr('multAluguel'),
        $entity->floatToStr('multEletrico'),
        $entity->floatToStr('multVendaval'),
        $entity->floatToStr('multIncendioRes'),
        $entity->floatToStr('multConteudoRes'),
        $entity->floatToStr('multAluguelRes'),
        $entity->floatToStr('multEletricoRes'),
        $entity->floatToStr('multVendavalRes'),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'index')); ?>";
        envia(tar,'buscar',formName);
    }    
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');  
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }  
    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }  
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>