<h1>Comissaos</h1>
<br />

<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'comissaos','action'=>'new')); ?>"><i class="icon-plus"></i>Nova Comissao</a>
</p>
<?php
$coluns = array('ID','Administradora','Comissão','Inicio','Fim','Status','Ação');
$td     = array('','','class="r"','','','','');
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getAdministradora(),
        $entity->floatToStr('Comissao'),
        $entity->getInicio(),
        $entity->getFim(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="GET">
    <input type="hidden" name="subOpcao" id="subOpcao">
</form>
<script language="javascript">
    function edit(id){
        var tar = "<?php echo $this->url('livraria-admin-interna',array('controller'=>'comissaos','action'=>'edit','id'=>'')); ?>";
        envia(tar + id);
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url('livraria-admin-interna',array('controller'=>'comissaos','action'=>'delete','id'=>'')); ?>";
        envia(tar + id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>