<h3>Escolha a Administradora</h3>

<br />
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin-interna',array('controller'=>'orcamentos','action'=>'new')));

$form->prepare();
echo 
$this->FormDefault(['legend' => 'Escolha a Administradora', 'hidden' => 'id'],'inicio',$this, $form),
    "<td>\r",
        $this->FormDefault(['ajaxStatus','autoComp','subOpcao','administradora'],'hidden'),
        $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'icone'),
    "</td>\r",
$this->FormDefault(['submit' => 'enviar'],'fim');

?>

<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    
    var tar = '<?php echo $this->url($this->matchedRouteName,$this->params); ?>';
    var formName = '<?php echo $this->formName ?>';
    function autoCompAdministradora(){
        document.getElementById('autoComp').value = 'administradoraDesc';
        var filtros = 'administradoraDesc,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscaAdministradora()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }
    function buscaAdministradora(){
        envia(tar,'escolher',formName);
    }

    function salvar(){
        buscaAdministradora();
        return false;
    }

</script>