<h1>Escolha uma opção.</h1>
<br />
<br />
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'orcamentos','action'=>'new')); ?>">Novo Orçamento.</a>
</p>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'orcamentos','action'=>'listarOrcamentos')); ?>">Listar Orçamentos.</a>
</p>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'orcamentos','action'=>'buscarAbertos')); ?>">Orçamentos a serem fechados.</a>
</p>
<br />
<br />