<h1>Orçamentos e Renovações</h1>
<br />
<style type="text/css">
#delobs, #delobs2, #retobs {
    left:250px;
    margin:10px;
    padding:20px;
    position:absolute;
    top:300px;
    width:650px;
    background-color: #ffffff;
    border: solid #000 1px;
}
</style>
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<?php

    $user = $this->UserIdentity('LivrariaAdmin');
    $form = $this->form; 
    $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
    $form->prepare();
    echo 
    $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
        "\r<td>",
            $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp','user','locador','locatario','ordenador','ascdesc'], 'hidden'),
            $this->FormDefault(['name' => 'locadorNome','icone' => 'icon-search','js' => 'autoCompLocador()','span' => "popLocador' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['name' => 'locatarioNome','icone' => 'icon-search','js' => 'autoCompLocatario()','span' => "popLocatario' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['refImovel' => 'text']),
        "</td>\r<td>",
            $this->FormDefault(['id' => 'text']),
        "</td>\r",
    "</tr><tr>\r",
        "\r<td>",
            $this->FormDefault([
                'name' => 'usuarioNome',
                'icone' => 'icon-search',
                'js' => 'autoCompUsuario()',
                'span' => "popUser' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['dataI'], 'calend'),
        "</td>\r<td>",
            $this->FormDefault(['dataF'], 'calend'),
        "</td><td>\r",
            $this->FormDefault(['fechadoId' => 'text']),
        "</td>\r",
    "</tr><tr>\r",
        "<td>\r",
            $this->FormDefault(['administradora'=>'hidden']),
            $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['status'=>'radio']),
        "</td><td>\r",
            ($user->getTipo() == 'admin')?$this->FormDefault(['validade'=>'radio']):'',
        "</td><td style='vertical-align: middle;'>\r",
            $this->FormDefault(['enviar'], 'submitOnly'),
        "</td>\r",

    $this->FormDefault([],'fim');

echo '<form name="form" id="form" method="POST">';

$coluns = array(
    'Ação',
    'Selecionar<br><label class="checkbox th" onClick="setCheckbox()"><input type="checkbox" id="CheckTodos" value="">Todos</label>',
    'Status',
    'Ref Imovél',
    'Locador',
    'Locatário',
    'Local do Risco',
    'Inicio Vigência',
    'Atividade',
    'Parc.',
    'Vlr Parc.',
    'Valor',
    'Proposta',
);

$func = array(      
    '',           
    '',     
    "buscar('l.status')",     
    "buscar('l.refImovel')",  
    "buscar('ld.nome')",    
    "buscar('lc.nome')",  
    "buscar('i.rua')",  
    "buscar('l.inicio')",  
    "buscar('l.atividade')",  
    "",  
    "",  
    "buscar('l.premioTotal')",
    "buscar('l.id')",        
);

$td     = array(
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap class="r"',
    '',
    '',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap class="r"',
    'nowrap class="r"',
    'class="r"',
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'first', 'tr' => 'class="f3"', 'func' => $func));


if($user->getTipo() == "admin"){
    $lambda = function($value, &$data) {
        echo "\t<td nowrap>";
        switch ($data[2]) {
            case "Cancelado Reno":
                echo '<span class="add-on hand" onClick="reativar(\'', $value, '\')"><i class="icon-fire"></i>Reativar.</span>';
                echo '<span class="add-on hand" onClick="getLogsReno(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Ren</span>';
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';
                break;
            case "Cancelado Orça":
            case "Cancelado":
                echo '<span class="add-on hand" onClick="reativar(\'', $value, '\')"><i class="icon-fire"></i>Reativar.</span>';
                echo '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Orc</span>';
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';
                break;
            case "Renovação": 
            case "Importado": 
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                '<span class="add-on hand" onClick="del(\'', $value, '\',1)"><i class="icon-remove"></i>Canc.</span>',
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';
                echo '<span class="add-on hand" onClick="getLogsReno(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Ren</span>';
                break;
            case "Orçamento": 
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                '<span class="add-on hand" onClick="del(\'', $value, '\',0)"><i class="icon-remove"></i>Canc.</span>',
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';
                echo '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Orc</span>';
                break;
            case "Fechado":
            case "Fechou Orça":
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                '<span class="add-on hand" onClick="del(\'', $value, '\',2)"><i class="icon-remove"></i>Canc.</span>',
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>';
                echo '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Orc</span>';
                break;
            case "Fechado":
            case "Fechou Reno":
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                '<span class="add-on hand" onClick="del(\'', $value, '\',3)"><i class="icon-remove"></i>Canc.</span>',
                '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>';
                echo '<span class="add-on hand" onClick="getLogsReno(\'', $value, '\')"><i class="icon-eye-open"></i>Logs Ren</span>';
                break;
            default:
                echo '<span class="add-on hand">Sem Ação</span>';
        }
        echo "</td>\n";
    };
}else{   
    $lambda = function($value,&$data){  
        echo "\t<td nowrap>";
        switch ($data[2]) {
            case "Cancelado Reno":
            case "Cancelado Orça":
            case "Cancelado":
                echo '<span class="add-on hand">cancelado</span>';
                break;
            case "Fechado":
            case "Fechou Reno":
            case "Fechou Orça":
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>';
                break;
            case "Orçamento": 
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\',0)"><i class="icon-remove"></i>Canc.</span>',
                     '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';   
                break;
            case "Renovação": 
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\',1)"><i class="icon-remove"></i>Canc.</span>',
                     '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';   
                break;
            case "Importado": 
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Canc.</span>',
                     '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';   
                break;
            default:
                echo '<span class="add-on hand">Sem Ação</span>';
        }
        echo "</td>\n";  
    };   
}      
$this->ViewIndex('setFuncEdit',$lambda); 


foreach($this->data as $entity){ 
    $status = $entity->getStatus();
    if($status == 'A' OR $status == 'R'){
        $campo1 = '<label class="checkbox"><input type="checkbox" name="Checkeds[]" value="'. $entity->getId() .'"></label>';        
    }else if($status == 'F'){
        $campo1 = '<label class="checkbox"><input type="checkbox" name="CheckedsFechados[]" value="'. $entity->getId() .'"></label>';        
    }  else {
        $campo1 = '';
    }
    if($entity->getFormaPagto() != "01"){
        $vlrParc = number_format($entity->getPremioTotal() / $entity->getFormaPagto(), 2, ',', '.');
    }else{
        $vlrParc = '-';
    }
    $linha = array(
        $entity->getId(),
        $campo1,
        $entity->getStatus('str'),
        $entity->getRefImovel(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->getImovel(),
        $entity->getInicio(),
        $entity->getAtividade(),
        $entity->getFormaPagto(),
        $vlrParc,
        $entity->floatToStr('premioTotal'),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha, 'tr' => 'class="f3"'));
}
echo $this->ViewIndex('close');

echo $this->FormDefault(['fecharSel'], 'submit');
?>
<br />
<div class="noPrint" align="center">
    <input type="button" name="fecharAll" id="fecharAll" class="btn-success" value="Fechar Todas Paginas" onclick="return fecharTodos()">
</div>
<br />
<div class="noPrint" align="center">
    <input type="button" name="cancelSel" id="cancelSel" class="btn-success" value="Cancelar Selecionados" onclick="return cancelSelecionados()">
</div>
<?php
    // Usuario Administrador pode alterar data da Vigencia.    
    if ($user->getTipo() == 'admin') :
?>
    <br />
    <div class="noPrint" align="center">
        <table>
            <tr>
                <td style="padding-left:1cm;">
        <div cla|ss="input-append" id="popchangeInicio">
            <label for="changeInicio">Inicio da Vigência</label>
            <input name="changeInicio" id="changeInicio" placeholder="dd/mm/yyyy" type="text" value="" onkeydown="return changeEnterToTab(this,event)" onblur="toUp(this)" onclick="displayCalendar(this,dateFormat,this)" onkeyup="formataData(this);">
            <span class="add-on hand" onClick="cleanInput('changeInicio')">
                <i class="icon-remove"></i></span>
            <span class="add-on hand" onClick="displayCalendar(document.getElementById('changeInicio'),dateFormat,this)">
                <i class="icon-calendar"></i></span>
        </div> 
                    
                </td>
                <td style="padding-left:1cm;">
        <div class="input-append" id="popchangeValidade">
            <label for="validade">Validade</label>
            <label><input type="radio" name="changeValidade" value="" checked onkeypress="return changeEnterToTab(this,event)" >Manter</label>
            <label><input type="radio" name="changeValidade" value="mensal"   onkeypress="return changeEnterToTab(this,event)" >Mensal</label>
            <label><input type="radio" name="changeValidade" value="anual"    onkeypress="return changeEnterToTab(this,event)" >Anual</label>
        </div>   
                    
                </td>
                <td style="padding-left:1cm;">
        <div class="input-append" id="popchangeValidade">
            <label for="validade">Forma de Pagamento</label>
            <label><input type="radio" name="changeFormaPagto" value="" checked onkeypress="return changeEnterToTab(this,event)" >Manter</label>
            <label><input type="radio" name="changeFormaPagto" value="01"       onkeypress="return changeEnterToTab(this,event)" >A vista(no ato)</label>
            <label><input type="radio" name="changeFormaPagto" value="02"       onkeypress="return changeEnterToTab(this,event)" >2 vezes(1+1)</label>
            <label><input type="radio" name="changeFormaPagto" value="03"       onkeypress="return changeEnterToTab(this,event)" >3 vezes(1+2)</label>
        </div>   
                    
                </td>
                <td style="padding-left:1cm;">
                    
        <input type="button" name="cancelSel" id="change" class="btn-success" value="Alterar Vigência Inicial e Validade Selecionados" onclick="return changeDateAndValidity()">
                </td>
            </tr>
        </table>    
                  
                
                
    </div>
<?php
    endif ;
?>
<br />
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
    <input type="hidden" name="orcamento" id="orcamento">
    <input type="hidden" name="renovacao" id="renovacao">
<div id="delobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoNaoFechou">Motivo de não fechar este orçamento.</label>
                    <textarea name="motivoNaoFechou" id="motivoNaoFechou" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir()"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:deleltar();"><i class="icon-trash"></i>Cancelar!</a>
            </td>
        </tr>
    </table>
</div>    
<div id="delobs2">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao2">
                    <label for="motivoNaoFechou2">Motivo de não fechar este(s) orçamento(s).</label>
                    <textarea name="motivoNaoFechou2" id="motivoNaoFechou2" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir('delobs2')"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:delVarios();"><i class="icon-trash"></i>Cancelar Todos!</a>
            </td>
        </tr>
    </table>
</div>   
<div id="retobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoReativa">Motivo para reativar este registro.</label>
                    <textarea name="motivoReativa" id="motivoReativa" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir('retobs')"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:reativando();"><i class="icon-fire"></i>Reativar!</a>
            </td>
        </tr>
    </table>
</div>   
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar',null,id);
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo',null,'');        
    }
    function changeDateAndValidity(){
//        if($('#changeInicio').val() === ''){
//            alert('Preencha a vigência inicial por favor!');
//            $('#changeInicio').focus();
//            return false;
//        }        
        if(!oneChecked(false) && !oneCheckedFechados())return false;
        var msg = "Deseja realmente alterar os registros selecionados? \n Aviso esta operação não poderá ser disfeita.";
        if(!confirm(msg))return false; 
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'changeDateValidity')); ?>";
        envia(tar,'novo',null,''); 
        return false;        
    }
    function getLogs(id){
        document.getElementById('id2').value = id ;
        document.getElementById('orcamento').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'logs','action'=>'logOrcamento')); ?>";
        envia(tar,id,null,'');        
    }
    function getLogsReno(id){
        document.getElementById('id2').value = id ;
        document.getElementById('renovacao').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'logs','action'=>'logRenovacao')); ?>";
        envia(tar,id,null,'');        
    }    
    function del(id, opt){
        var motivo = document.getElementById('delobs');
        motivo.style.display = 'none';
        var tipo = '';
        switch(opt){
            case 0:
                tipo = 'e Orçamento ';
                break;
            case 1:
                tipo = 'a Renovação ';
                break;
            case 2:
                tipo = 'e Orçamento Fechado ';
                break;
            case 3:
                tipo = 'a Renovação Fechada ';
                break;
        }
        var msg = "Deseja realmente cancelar est" + tipo + "?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;
    }  
    function reativar(id){
        var motivo = document.getElementById('retobs');
        motivo.style.display = 'none';
        var msg = "Deseja realmente Reativar este (orçamento ou Renovação)?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;        
    }
    function desistir(id){
        if(id == null){
            id = 'delobs';
        }
        document.getElementById(id).style.display='none';
        document.getElementById('id2').value = '' ;
    }
    function deleltar(){
        var id = document.getElementById('id2').value;
        if(id == '')return;
        var obs = document.getElementById('motivoNaoFechou').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
            return;
        }
        var palavras = obs.split(' ');
        if(palavras.length < 5){
            alert('No minimo 5 palavras devem ser Digitadas');
            return;
        }            
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        envia(tar,id,null,'');        
    }
    
    function reativando(){
        //alert('Em construção em breve estará liberada !!! =) ');
        //return;
        var id = $('#id2').val();
        if(id == ''){
            return;
        }
        var obs = $('#motivoReativa').val();
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
            return;
        }
        var palavras = obs.split(' ');
        if(palavras.length < 3){
            alert('No minimo 3 palavras devem ser Digitadas');
            return;
        }            
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'reativa')); ?>";
        envia(tar,id,null,'');  
    }

    function cancelSelecionados(){
        if(!oneChecked())return;
        var motivo = document.getElementById('delobs2');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar orçamento(s) selecionados ?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        
    }
    
    function oneChecked(msg){
        //Verificar se algum registro foi marcado
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            if(elems[i].checked){
                return true;
            }
        }
        if(msg == null || msg){
            alert("Nenhum registro foi selecionado!!");            
        }
        return false;
    }
    
    function oneCheckedFechados(){
        //Verificar se algum registro foi marcado
        var elems = document.getElementsByName('CheckedsFechados[]');
        for (i=0; i < elems.length; i++){
            if(elems[i].checked){
                return true;
            }
        }
        alert("Nenhum registro foi selecionado!!");
        return false;
    }

    function delVarios(){
        var obs = document.getElementById('motivoNaoFechou2').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
            return;
        }
        var palavras = obs.split(' ');
        if(palavras.length < 5){
            alert('No minimo 5 palavras devem ser Digitadas');
            return;
        } 
        
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delVarios')); ?>";
        envia(tar,'',null,''); 
        return false;
    }

    var dateFormat = 'dd/mm/yyyy';
    var formName = '<?php echo $this->formName ?>';
    function buscar(order){
        if($('#locadorNome').val() == ''){
            $('#locador').val('');
        }
        if($('#locatarioNome').val() == ''){
            $('#locatario').val('');
        }
        if($('#usuarioNome').val() == ''){
            $('#user').val('');
        }
        if($('#administradoraDesc').val() == ''){
            $('#administradora').val('');
        }
        if(($('#administradora').val() == '')
                &&($('#dataI').val() == '')
                &&($('#locatario').val() == '')
                &&($('#locador').val() == '')
                &&($('#id').val() == '')
                &&($('#refImovel').val() == '')
                &&($('#usuarioNome').val() == '')
          )
        {
            alert('Atenção é necessário preencher alguns filtro:\n Ex: Administradora ou Periodo ou Locador or Locatario!');
            return false;
        }
        if(order != null){
            if($('#ascdesc').val() == 'ASC' && $('#ordenador').val() == order){
                $('#ascdesc').val('DESC');
            }else{
                $('#ascdesc').val('ASC');
            }
            $('#ordenador').val(order);   
        }
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'listarOrcamentos')); ?>";
        envia(tar,'buscar',formName,'');
        return false;
    }  
    function autoCompUsuario(){
        document.getElementById('autoComp').value = 'usuarioNome';
        var filtros = 'autoComp,usuarioNome';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'users','action'=>'autoComp')); ?>";
        var returns = Array('user','usuarioNome');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popUser',returns,'2',functionCall);
    }
    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }  

    function autoCompLocador(){
        $('#autoComp').val('locadorNome');
        var filtros = 'locadorNome,administradora';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locadors','action'=>'autoComp')); ?>";
        var returns = Array('locador','locadorNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocador',returns,'4',functionCall);
    }

    function autoCompLocatario(){
        $('#autoComp').val('locatarioNome');
        var filtros = 'locatarioNome,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locatarios','action'=>'autoComp')); ?>";
        var returns = Array('locatario','locatarioNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocatario',returns,'4',functionCall);
    }
    function setCheckbox(){
        var todos = document.getElementById('CheckTodos');
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            elems[i].checked = todos.checked;
        }
        var elems = document.getElementsByName('CheckedsFechados[]');
        for (i=0; i < elems.length; i++){
            elems[i].checked = todos.checked;
        }
    }
    function fecharSelecionados(){
        if(!oneChecked())return false;    
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'fecharSeguros')); ?>";
        envia(tar,'novo',null,''); 
        return false;
    }
    
    function fecharTodos(){
        var msg = "Deseja realmente fechar os seguros de todas as paginas.\n\n PS não será possivel reverter em caso de erro!! ";
        if(!confirm(msg)){
            return false;
        }
        var aux = false;    
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'fecharTodosSeguros')); ?>";
        envia(tar,'todos',formName,''); 
        return false;
    }

    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    }

    document.getElementById('delobs').style.display = 'none';
    
    document.getElementById('retobs').style.display = 'none';
    
    document.getElementById('delobs2').style.display = 'none';
    
    //Funcao jquey para janela de flash mensagem rolar conforme o scrool
    $(document).ready(function(){
        try{
            var y_fixo = 300 + $("#delobs").offset().top;
            var y_fixo = 300 + $("#retobs").offset().top;
            var y_fixo = 300 + $("#delobs2").offset().top;
        }catch(e){
            return ;
        }
        $(window).scroll(function () {
            $("#delobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
            $("#retobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
            $("#delobs2").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
        });
    });
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>