<h1>Orçamentos e Renovações</h1>
<br />
<style type="text/css">
#delobs, #delobs2 {
    left:150px;
    margin:0;
    padding:10px;
    position:absolute;
    top:80%;
    width:650px;
    background-color: #ffffff;
    border: solid #000 1px;
}
</style>
<?php if(count($flashMessages)) : ?>
<div class="control-group error">
<ul class="help-inline">
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
<?php

    $user = $this->UserIdentity('LivrariaAdmin');
    $form = $this->form; 
    $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
    $form->prepare();
    echo 
    $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
        "\r<td>",
            $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp','user','locador','locatario'], 'hidden'),
            $this->FormDefault(['name' => 'locadorNome','icone' => 'icon-search','js' => 'autoCompLocador()','span' => "popLocador' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['name' => 'locatarioNome','icone' => 'icon-search','js' => 'autoCompLocatario()','span' => "popLocatario' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['refImovel' => 'text']),
        "</td>\r<td>",
            $this->FormDefault(['id' => 'text']),
        "</td>\r",
    "</tr><tr>\r",
        "\r<td>",
            $this->FormDefault([
                'name' => 'usuarioNome',
                'icone' => 'icon-search',
                'js' => 'autoCompUsuario()',
                'span' => "popUser' style='position:absolute"],'icone'),
        "</td>\r<td>",
            $this->FormDefault(['dataI'], 'calend'),
        "</td>\r<td>",
            $this->FormDefault(['dataF'], 'calend'),
        "</td><td style='vertical-align: middle;' rowspan='2'>\r",
            $this->FormDefault(['enviar'], 'submitOnly'),
        "</td>\r",
    "</tr><tr>\r",
        "<td>\r",
            $this->FormDefault(['administradora'=>'hidden']),
            $this->FormDefault(['name' => 'administradoraDesc','icone' => 'icon-search','js' => 'autoCompAdministradora()','span' => "popAdministradora' style='position:absolute"],'icone'),
        "</td><td>\r",
            $this->FormDefault(['status'=>'radio']),
        "</td><td>\r",
            ($user->getTipo() == 'admin')?$this->FormDefault(['validade'=>'radio']):'',
        "</td><td>\r",
        "</td>\r",

    $this->FormDefault([],'fim');

echo '<form name="form" id="form" method="POST">';

$coluns = array(
    'Ação',
    'Selecionar<br><label class="checkbox" onClick="setCheckbox()"><input type="checkbox" id="CheckTodos" value="">Todos</label>',
    'Status',
    'Ref Imovél',
    'Locador',
    'Locatário',
    'Local do Risco',
    'Inicio Vigência',
    'Atividade',
    'Valor',
);
$td     = array(
    'nowrap',
    'nowrap class="r"',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'nowrap',
    'class="r"'
);
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'first'));


if($user->getTipo() == "admin"){
    $lambda = function($value,&$data){ 
        echo "\t<td nowrap>";
        switch ($data[2]) {
            case "C":
                echo '<span class="add-on hand" onClick="getLogs(\'', $value, '\')"><i class="icon-eye-open"></i>Logs</span>';
                break;
            case "A":            case "I":            case "R":            case "F":
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Canc.</span>',
                     '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';   
                break;
            default:
                echo '<span class="add-on hand">Sem Ação</span>';
        }
        echo "</td>\n";   
    };     
}else{   
    $lambda = function($value,&$data){  
        echo "\t<td nowrap>";
        switch ($data[2]) {
            case "C":
                echo '<span class="add-on hand">cancelado</span>';
                break;
            case "F":
                echo '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Imprimir</span>';
                break;
            case "A":            case "I":            case "R":
                echo '<span class="add-on hand" onClick="edit(\'', $value, '\')"><i class="icon-pencil"></i>Editar</span>',
                     '<span class="add-on hand" onClick="del(\'', $value, '\')"><i class="icon-remove"></i>Canc.</span>',
                     '<span class="add-on hand" onClick="printPdf(\'', $value, '\')"><i class="icon-print"></i>Impr.</span>';   
                break;
            default:
                echo '<span class="add-on hand">Sem Ação</span>';
        }
        echo "</td>\n";  
    };   
}      
$this->ViewIndex('setFuncEdit',$lambda); 


foreach($this->data as $entity){ 
    $status = $entity->getStatus();
    if($status == 'A' OR $status == 'R'){
        $campo1 = '<label class="checkbox"><input type="checkbox" name="Checkeds[]" value="'. $entity->getId() .'">'. $entity->getId() .'/'. $entity->getCodAno() .'</label>';        
    }else{
        $campo1 = $entity->getId() .'/'. $entity->getCodAno() ;
    }
    $linha = array(
        $entity->getId(),
        $campo1,
        $entity->getStatus(),
        $entity->getRefImovel(),
        $entity->getLocadorNome(),
        $entity->getLocatarioNome(),
        $entity->getImovel(),
        $entity->getInicio(),
        $entity->getAtividade(),
        $entity->floatToStr('premioTotal')
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');

echo $this->FormDefault(['fecharSel'], 'submit');
?>
<br />
<div class="noPrint" align="center">
    <input type="button" name="cancelSel" id="cancelSel" class="btn-success" value="Fechar Todas Paginas" onclick="return fecharTodos()">
</div>
<br />
<div class="noPrint" align="center">
    <input type="button" name="cancelSel" id="cancelSel" class="btn-success" value="Cancelar Selecionados" onclick="return cancelSelecionados()">
</div>
<br />
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
    <input type="hidden" name="orcamento" id="orcamento">
<div id="delobs">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao">
                    <label for="motivoNaoFechou">Motivo de não fechar este orçamento.</label>
                    <textarea name="motivoNaoFechou" id="motivoNaoFechou" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir()"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:deleltar();"><i class="icon-trash"></i>Cancelar!</a>
            </td>
        </tr>
    </table>
</div>    
<div id="delobs2">
    <table width="100%">
        <tr>
            <td>
                <div class="input-append" id="popobservacao2">
                    <label for="motivoNaoFechou2">Motivo de não fechar este(s) orçamento(s).</label>
                    <textarea name="motivoNaoFechou2" id="motivoNaoFechou2" rows="6" class="span6"></textarea>
                </div>
            </td>
            <td valign='top'>
                <a href="javascript:desistir('delobs2')"><i class="icon-backward"></i>Desisitir!</a>
                <br><br><br><a href="javascript:delVarios();"><i class="icon-trash"></i>Cancelar Todos!</a>
            </td>
        </tr>
    </table>
</div>    
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar',null,'');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo',null,'');        
    }
    function getLogs(id){
        document.getElementById('id2').value = id ;
        document.getElementById('orcamento').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> 'logs','action'=>'logOrcamento')); ?>";
        envia(tar,id,null,'');        
    }
    function del(id){
        var motivo = document.getElementById('delobs');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar este orçamento?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        document.getElementById('id2').value = id ;
    }  
    function desistir(id){
        if(id == null){
            id = 'delobs';
        }
        document.getElementById(id).style.display='none';
        document.getElementById('id2').value = '' ;
    }
    function deleltar(){
        var id = document.getElementById('id2').value;
        var obs = document.getElementById('motivoNaoFechou').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
            return;
        }
        if(id == '')return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        envia(tar,id,null,'');        
    }

    function cancelSelecionados(){
        //Verificar se algum orcamento foi marcado
        var aux = false;
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            if(elems[i].checked){
                aux = true;
                break;
            }
        }
        if(!aux){
            alert("Nenhum registro foi selecionado!!");
            return false;
        }
    
        var motivo = document.getElementById('delobs2');
        motivo.style.display = 'none';
        var msg = "Deseja realmente cancelar orçamento(s) selecionados ?";
        if(!confirm(msg))return;
        motivo.style.display = 'block';
        
    }

    function delVarios(){
        var obs = document.getElementById('motivoNaoFechou2').value;
        if(obs == ''){
            alert('Digite o motivo por favor!!!');
            return;
        }
        
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delVarios')); ?>";
        envia(tar,'',null,''); 
        return false;
    }

    var dateFormat = 'dd/mm/yyyy';
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        if($('#locadorNome').val() == ''){
            $('#locador').val('');
        }
        if($('#locatarioNome').val() == ''){
            $('#locatario').val('');
        }
        if($('#usuarioNome').val() == ''){
            $('#user').val('');
        }
        if($('#administradoraDesc').val() == ''){
            $('#administradora').val('');
        }
        if(($('#administradora').val() == '')&&($('#dataI').val() == '')&&($('#locatario').val() == '')&&($('#locador').val() == '')){
            alert('Atenção é necessário preencher alguns filtro:\n Ex: Administradora ou Periodo ou Locador or Locatario!');
            return false;
        }
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'listarOrcamentos')); ?>";
        envia(tar,'buscar',formName,'');
        return false;
    }  
    function autoCompUsuario(){
        document.getElementById('autoComp').value = 'usuarioNome';
        var filtros = 'autoComp,usuarioNome';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'users','action'=>'autoComp')); ?>";
        var returns = Array('user','usuarioNome');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popUser',returns,'2',functionCall);
    }
    function autoCompAdministradora(){
        var filtros = 'administradoraDesc';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'administradoras','action'=>'autoComp')); ?>";
        var returns = Array('administradora','administradoraDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAdministradora',returns,'2',functionCall);
    }  

    function autoCompLocador(){
        $('#autoComp').val('locadorNome');
        var filtros = 'locadorNome,administradora';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locadors','action'=>'autoComp')); ?>";
        var returns = Array('locador','locadorNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocador',returns,'4',functionCall);
    }

    function autoCompLocatario(){
        $('#autoComp').val('locatarioNome');
        var filtros = 'locatarioNome,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locatarios','action'=>'autoComp')); ?>";
        var returns = Array('locatario','locatarioNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocatario',returns,'4',functionCall);
    }
    function setCheckbox(){
        var todos = document.getElementById('CheckTodos');
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            elems[i].checked = todos.checked;
        }
    }
    function fecharSelecionados(){
        //Verificar se algum orcamento foi marcado
        var aux = false;
        var elems = document.getElementsByName('Checkeds[]');
        for (i=0; i < elems.length; i++){
            if(elems[i].checked){
                aux = true;
                break;
            }
        }
        if(!aux){
            alert("Nenhum registro foi selecionado!!");
            return false;
        }
    
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'fecharSeguros')); ?>";
        envia(tar,'novo',null,''); 
        return false;
    }
    
    function fecharTodos(){
        var msg = "Deseja realmente fechar os seguros de todas as paginas.\n\n PS não será possivel reverter em caso de erro!! ";
        if(!confirm(msg)){
            return false;
        }
        var aux = false;    
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'fecharTodosSeguros')); ?>";
        envia(tar,'todos',formName,''); 
        return false;
    }

    function printPdf(id){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'imprimiSeguro')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id,null,'new');  
        
    }

    document.getElementById('delobs').style.display = 'none';
    
    document.getElementById('delobs2').style.display = 'none';
    
    $(document).ready(function(){
        var y_fixo = 250 + $("#delobs").offset().top;
        $(window).scroll(function () {
            $("#delobs").stop().animate({
                top: y_fixo+$(document).scrollTop()+"px"
                },{duration:500,queue:false}
            );
        });
    });
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>