<?php
if ($this->pageCount):
    ?>
<div class="noPrint">
    <div class="pagination pagination-centered">
        <ul>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url($this->route->getMatchedRouteName(), $this->route->setParam('page', $this->first)->getParams()), '?', rand(); ?>"><i class="icon-fast-backward"></i></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#"><i class="icon-fast-backward"></i></a></li>
            <?php endif; ?>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url($this->route->getMatchedRouteName(), $this->route->setParam('page', $this->previous)->getParams()), '?', rand(); ?>"><i class="icon-step-backward"></i></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#"><i class="icon-step-backward"></i></a></li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route->getMatchedRouteName(), $this->route->setParam('page', $page)->getParams()), '?', rand(); ?>"><?php echo $page; ?></a>
                    </li>               
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>               
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url($this->route->getMatchedRouteName(), $this->route->setParam('page', $this->next)->getParams()), '?', rand(); ?>"><i class="icon-step-forward"></i></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#"><i class="icon-step-forward"></i></a></li>
            <?php endif; ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url($this->route->getMatchedRouteName(), $this->route->setParam('page', $this->last)->getParams()), '?', rand(); ?>"><i class="icon-fast-forward"></i></a></li>
            <?php else: ?>
                <li class="disabled"><a href="#"><i class="icon-fast-forward"></i></a></li>
            <?php endif; ?>
        </ul>
    </div>
    <p>Total de Registros Encontrados <?php echo $this->totalItemCount; ?></p>
    <p>Itens por pagina <?php echo $this->currentItemCount; ?></p>
    <p>Total de paginas <?php echo $this->pageCount; ?></p>
</div>
<?php endif; ?>