<?php 
if($this->resultSet){
    echo "ok|s|";
    if($this->subOpcao =='Pesquisar'){
        echo 'X|c|',
             'X|c|',
             'End.|c|',
             'Apto/Blc|c|',
             'Compl.|c|',
             'Bairro|c|',
             'Cidade|c|',
             'UF|c|',
             'CEP|c|',
             'Ref.|c|',
             'Tel.|c|',
             "|s|";
    }
    $cont = 0;
    foreach($this->resultSet as $entity){
        if($cont > 0)echo "|s|";
        $cont++;
        echo $entity->getId(), "|c|"; 
        echo $entity->getRua() . ' n' . $entity->getNumero() . ', ' . $entity->getEndereco()->getBairro() . ',' . $entity->getEndereco()->getCidade(), "|c|"; 
        
        echo $entity->getRua(), ', n ' , $entity->getNumero(),    "|c|"; 
        $aptBlc = '';
        $apt = $entity->getApto();
        if (!empty($apt)) { // funçao empty so aceita variaveis como paramentro
            $aptBlc .= 'apt. ' . $apt;
        }
        $bloco = $entity->getBloco();
        if (!empty($bloco)) {
            $aptBlc .= ' BL. ' . $bloco;
        }       
        echo  $aptBlc,    "|c|"; 
        echo $entity->getEndereco()->getCompl(),  "|c|"; 
        echo $entity->getEndereco()->getBairro(), "|c|"; 
        echo $entity->getEndereco()->getCidade(), "|c|"; 
        echo $entity->getEndereco()->getEstado()->getSigla(), "|c|"; 
        echo $entity->getCep(),    "|c|"; 
        echo $entity->getRefImovel(),    "|c|"; 
        echo $entity->getTel(),    "|c|"; 
    }
}else
    echo "vazio|s|";