<h1>Imóveis</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Imovel</span></p>
<?php

    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['rua'], 'text'),
            "</td>\r<td>",
                $this->FormDefault(['refImovel'], 'text'),
            "</td>\r",
        "</tr><tr>\r",
            "<td>\r",
                $this->FormDefault(['locador'=>'hidden']),
                $this->FormDefault(['name' => 'locadorNome','icone' => 'icon-search','js' => 'autoCompLocador()','span' => "popLocador' style='position:absolute"],'icone'),
            "</td>\r<td>",
                $this->FormDefault(['locatario'=>'hidden']),
                $this->FormDefault(['name' => 'locatarioNome','icone' => 'icon-search','js' => 'autoCompLocatario()','span' => "popLocatario' style='position:absolute"],'icone'),
            "</td>\r",
        "</tr><tr>\r",
            "<td colspan=2 align=center>\r",
                $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp'], 'hidden'),
                $this->FormDefault(['enviar'], 'submitOnly'),
            "</td>\r",
        $this->FormDefault([],'fim');
    }

$coluns = array('ID','Locador','Locatario','Atividade','Ref.','Rua','Numero','Compl','Bloco','Apto','CEP','Status','Ação');
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getLocador(),
        $entity->getLocatario(),
        $entity->getAtividade(),
        $entity->getRefImovel(),
        $entity->getRua(),
        $entity->getNumero(),
        $entity->getEndereco()->getCompl(),
        $entity->getBloco(),
        $entity->getApto(),
        $entity->getCep(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'index')); ?>";
        if($('#locadorNome').val() == ''){
            $('#locador').val('');
        }
        if($('#locatarioNome').val() == ''){
            $('#locatario').val('');
        }
        envia(tar,'buscar',formName);
    }  
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
    function autoCompLocador(){
        document.getElementById('autoComp').value = 'locadorNome';
        var filtros = 'locadorNome,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locadors','action'=>'autoComp')); ?>";
        var returns = Array('locador','locadorNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocador',returns,'4',functionCall);
    }
    function autoCompLocatario(){
        document.getElementById('autoComp').value = 'locatarioNome';
        var filtros = 'locatarioNome,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'locatarios','action'=>'autoComp')); ?>";
        var returns = Array('locatario','locatarioNome');
        var functionCall = '';
        autoComp2(filtros,servico,'popLocatario',returns,'3',functionCall);
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>