<h1>Imovels</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Imovel</span></p>
<?php
$coluns = array('ID','Locador','Atividade','Rua','Numero','Compl','Bloco','Apto','CEP','Status','Ação');
$td     = array();
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $linha = array(
        $entity->getId(),
        $entity->getLocador(),
        $entity->getAtividade(),
        $entity->getRua(),
        $entity->getNumero(),
        $entity->getCompl(),
        $entity->getBloco(),
        $entity->getApto(),
        $entity->getCep(),
        $entity->getStatus(),
        $entity->getId(),
    );
    echo $this->ViewIndex('line',array('data' => $linha));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>