<br />
<br />
<br />
<br />
<br />
<br />
<div align="center">
<?php
$user = $this->UserIdentity('LivrariaAdmin');
echo '<h1>Bem Vindo, ', $user->getNome(), '.</h1>' ;
echo '<h2>ao Sistema de Incêndio / Locação.</h2>' ;
?>
<br />
<br />
<br />
<br />
<br />
<?php 
    echo '<p>Administradora:', $user->getAdministradora()['nome'],'<br /> Código(UE):', $user->getAdministradora()['id'], '</p>' ;           
?>    
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />