<?php
$user = $this->UserIdentity('LivrariaAdmin');
echo '<p>Bem Vindo, ', $user->getNome(), '.</p>' ;
echo '<p>Escolha uma das opções de cadastro.</p>' ;

$subMenu = $this->navigation('NavAdmin')->findOneByLabel('Relatórios');
?>

<div class="nav-collapse">
<?php
    if ($user) {
        switch ($user->getMenu()) {
        case 'adm':
            echo $this->navigation('NavAdmin')->menu()->setUlClass('nav')->renderMenu($subMenu); 
            break;
        case 'adm2':
            echo $this->navigation('NavNoAdmin')->menu()->setUlClass('nav')->renderMenu($subMenu); 
            break;
        case 'imob':
            echo $this->navigation('NavUser')->menu()->setUlClass('nav')->renderMenu($subMenu); 
            break;
        default:
            echo $this->navigation('Navigation')->menu()->setUlClass('nav'); 
            break;
        }
    } else {
        echo $this->navigation('Navigation')->menu()->setUlClass('nav');
    }
?>    
</div>