<br />
<div align="center">
<?php
$user = $this->UserIdentity('LivrariaAdmin');
?>
<img src="/images/suporte.jpg" />
<h1>Suporte.</h1> 
<br />
<br />
<br />
<br />
<h2>Em caso de duvidas contate o suporte.</h2> 
<br />
<br />
<br />
<h3>E-mail: <a href="mailto:incendiolocacao@vilavelha.com.br">incendiolocacao@vilavelha.com.br</a>.</h3> 
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />