<h1>Logs</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Log</span></p>
<?php
$coluns = array('ID','Usuario','Data Hora','Tabela','ID do Registro','Controller','Ação','Afetados','IP Computador','Ação');
$td     = array('','','','','','','','','','');
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));
     
foreach($this->data as $entity){ 
    $dePara = $entity->getDePara();
    if(substr($dePara, 0, 5) == 'Campo'){
        $data = explode(';', $dePara);
        $dePara = '<table class="table table-striped table-bordered table-hover table-condensed">';
        for($i = 0, $y = 1, $z = 2; $z < count($data); $i+=3, $y+=3, $z+=3){
            $dePara .= '<tr>';
            $dePara .= '<td>' . $data[$i] . '</td>';
            $dePara .= '<td>' . $data[$y] . '</td>';
            $dePara .= '<td>' . $data[$z] . '</td>';
            $dePara .= '</tr>';
        }
        $dePara .= '</table>';
    }
        
    echo $this->ViewIndex('line',array('data' => array(
        $entity->getId(),
        $entity->getUser(),
        $entity->getData('obj')->format('d/m/Y H:m:s'),
        $entity->getTabela(),
        $entity->getIdDoReg(),
        $entity->getController(),
        $entity->getAction(),
        $dePara,
        $entity->getIp(),
        $entity->getId()
    )));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>