<h1>Logs de Renovação</h1>
<br />
<?php
    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['ajaxStatus', 'subOpcao','autoComp','user'], 'hidden'),
                $this->FormDefault([
                    'name' => 'usuarioNome',
                    'icone' => 'icon-search',
                    'js' => 'autoCompUsuario()',
                    'span' => "popUser' style='position:absolute"],'icone'),
            "</td><td>\r",
                $this->FormDefault(['renovacao'], 'text'),
            "</td><td>\r",
                $this->FormDefault(['dataI'], 'calend'),
            "</td><td>\r",
                $this->FormDefault(['dataF'], 'calend'),
            "</td><td>\r",
            "</td><td style='vertical-align: middle;'>\r",
                $this->FormDefault(['enviar'], 'submitOnly'),
            "</td>\r",
        $this->FormDefault([],'fim');
    }
$coluns = array('ID','Usuario','Data Hora','Renovacao','Controller','Ação','Mensagem','Afetados','IP Computador');
$td     = [];
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'false'));
     
foreach($this->data as $entity){ 
    $dePara = $entity->getDePara();
    if(substr($dePara, 0, 5) == 'Campo'){
        $data = explode(';', $dePara);
        $dePara = '<table class="table table-striped table-bordered table-hover table-condensed">';
        for($i = 0, $y = 1, $z = 2; $z < count($data); $i+=3, $y+=3, $z+=3){
            $dePara .= '<tr>';
            $dePara .= '<td>' . $data[$i] . '</td>';
            $dePara .= '<td>' . $data[$y] . '</td>';
            $dePara .= '<td>' . $data[$z] . '</td>';
            $dePara .= '</tr>';
        }
        $dePara .= '</table>';
    }
        
    echo $this->ViewIndex('line',array('data' => array(
        $entity->getId(),
        $entity->getUser()->getNome(),
        $entity->getData('obj')->format('d/m/Y H:m:s'),
        $entity->getRenovacao()->getId(),
        $entity->getController(),
        $entity->getAction(),
        $entity->getMensagem(),
        $dePara,
        $entity->getIp()
    )));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var dateFormat = 'dd/mm/yyyy';
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        if(document.getElementById('usuarioNome').value == ''){
            document.getElementById('user').value = '';
        }
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'logRenovacao')); ?>";
        envia(tar,'buscar',formName);
    }  
    function autoCompUsuario(){
        document.getElementById('autoComp').value = 'usuarioNome';
        var filtros = 'autoComp,usuarioNome';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'users','action'=>'autoComp')); ?>";
        var returns = Array('user','usuarioNome');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popUser',returns,'2',functionCall);
    }
</script>
<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>