<h1>Logs de Fechados</h1>
<br />
<?php
$coluns = array('ID','Usuario','Data Hora','Fechado','Controller','Ação','Mensagem','Afetados','IP Computador');
$td     = [];
echo $this->ViewIndex('table'),
     $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'false'));
     
foreach($this->data as $entity){ 
    $dePara = $entity->getDePara();
    if(substr($dePara, 0, 5) == 'Campo'){
        $data = explode(';', $dePara);
        $dePara = '<table class="table table-striped table-bordered table-hover table-condensed">';
        for($i = 0, $y = 1, $z = 2; $z < count($data); $i+=3, $y+=3, $z+=3){
            $dePara .= '<tr>';
            $dePara .= '<td>' . $data[$i] . '</td>';
            $dePara .= '<td>' . $data[$y] . '</td>';
            $dePara .= '<td>' . $data[$z] . '</td>';
            $dePara .= '</tr>';
        }
        $dePara .= '</table>';
    }
        
    echo $this->ViewIndex('line',array('data' => array(
        $entity->getId(),
        $entity->getUser()->getNome(),
        $entity->getData('obj')->format('d/m/Y H:m:s'),
        $entity->getFechados()->getId(),
        $entity->getController(),
        $entity->getAction(),
        $entity->getMensagem(),
        $dePara,
        $entity->getIp()
    )));
}
echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
</script>
<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>