<h1>Classe Atividades</h1>
<br />

<p><span class="add-on hand" onClick="novo();"><i class="icon-plus"></i>Nova Classe Atividade</span></p>

<?php

    if(!isset($noFilter)){
        $form = $this->form; 
        $form->setAttribute('action', $this->url($this->matchedRouteName,$this->params));
        $form->prepare();
        echo 
        $this->FormDefault(['legend' => 'Filtro(s)'],'inicio',$this, $form),
            "<td>\r",
                $this->FormDefault(['atividade', 'ajaxStatus', 'subOpcao','autoComp'], 'hidden'),
                $this->FormDefault(['name' => 'atividadeDesc','icone' => 'icon-search','js' => 'autoCompAtividade()','span' => "popAtividade' style='position:absolute"],'iconeLine'),
                "</td>\r",
        $this->FormDefault([],'fim');
    }

    $coluns = array('ID','Seguradora','Atividade','Classe','Inicio','Fim','Status','Ação');
    $td     = array();
    echo $this->ViewIndex('table'),
         $this->ViewIndex('thead', array('coluns' => $coluns, 'tdopt' => $td,'editLine' => 'last'));

    foreach($this->data as $entity){ 
        $linha = array(
            $entity->getId(),
            $entity->getSeguradora(),
            $entity->getAtividade()->getDescricao(),
            $entity->getClasseTaxas()->getDescricao(),
            $entity->getInicio(),
            $entity->getFim(),
            $entity->getStatus(),
            $entity->getId(),
        );
        echo $this->ViewIndex('line',array('data' => $linha));
    }
    echo $this->ViewIndex('close');
?>
<br />
<form name="form" id="form" method="POST">
    <input type="hidden" name="subOpcao" id="subOpcao2">
    <input type="hidden" name="id" id="id2">
</form>
<script language="javascript">
    var formName = '<?php echo $this->formName ?>';
    function buscar(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'index')); ?>";
        envia(tar,'buscar',formName);
    }  
    function edit(id){
        document.getElementById('id2').value = id ;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'edit')); ?>";
        envia(tar,'editar');
    }    
    function novo(){
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'new')); ?>";
        envia(tar,'novo');        
    }    
    function del(id){
        var msg = "Deseja realmente excluir este registro?";
        if(!confirm(msg))return;
        var tar = "<?php echo $this->url($this->matchedRouteName,array('controller'=> $this->params['controller'],'action'=>'delete')); ?>";
        document.getElementById('id2').value = id ;
        envia(tar,id);        
    }
    function autoCompAtividade(){
        //document.getElementById('autoComp').value = 'atividadeDesc';
        var filtros = 'atividadeDesc,autoComp';
        var servico = "<?php echo $this->url('livraria-admin',array('controller'=>'atividades','action'=>'autoComp')); ?>";
        var returns = Array('atividade','atividadeDesc');
        var functionCall = 'buscar()';
        autoComp2(filtros,servico,'popAtividade',returns,'2',functionCall);
    }
</script>

<?php echo $this->paginationControl($this->data,'Sliding','paginator',array('route' => $this->route)); ?>